In [48]:
import numpy as np
#import matplotlib.pyplot as plt
import pandas as pd
#import seaborn as sns
#sns.set()
from sklearn.model_selection import train_test_split

from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor
from sklearn import metrics

In [49]:
data = pd.read_excel(r'C:\Users\Hpvictus1\Downloads\income_est.xlsx')
data

,account,age,amount,balance,card_present_flag,customer_id,date,first_name,gender,latitude,longitude,merchant_code,merchant_id,merchant_state,merchant_suburb,movement,status,transaction_id,txn_description,bin_age,year,month,day,hour,minute,dow,payment_period,annual_salary
0,ACC-1598451071,26,16.25,35.39,1.0,CUS-2487424745,2018-08-01,Diana,F,-27.95,153.41,NaN,81c48296-73be-44a7-befa-d053f48ce7cd,QLD,Ashmore,debit,authorized,a623070bfead4541a6b0fff8a09e706c,POS,20-30,2018,8,1,1,1,Wednesday,7,52856
1,ACC-1598451071,26,14.19,21.20,0.0,CUS-2487424745,2018-08-01,Diana,F,-27.95,153.41,NaN,830a451c-316e-4a6a-bf25-e37caedca49e,NSW,Sydney,debit,authorized,13270a2a902145da9db4c951e04b51b9,SALES-POS,20-30,2018,8,1,1,13,Wednesday,7,52856
2,ACC-1598451071,26,3.25,17.95,1.0,CUS-2487424745,2018-08-01,Diana,F,-27.95,153.41,NaN,b4e02c10-0852-4273-b8fd-7b3395e32eb0,QLD,Mermaid Beach,debit,authorized,329adf79878c4cf0aeb4188b4691c266,SALES-POS,20-30,2018,8,1,1,51,Wednesday,7,52856
3,ACC-1598451071,26,14.10,3.85,1.0,CUS-2487424745,2018-08-01,Diana,F,-27.95,153.41,NaN,f2ef6270-cf91-409f-a6a2-fbd6735ea500,NSW,Byron Bay,debit,authorized,1c12c9ad77894ef8b507fb091e41e928,POS,20-30,2018,8,1,8,9,Wednesday,7,52856
4,ACC-1598451071,26,10.67,1006.85,1.0,CUS-2487424745,2018-08-01,Diana,F,-27.95,153.41,NaN,44abc19c-aa5c-40bd-b1d0-9b2f236189ea,QLD,Bundall,debit,authorized,cd0113426970425a8524e55f4079408f,POS,20-30,2018,8,1,18,19,Wednesday,7,52856
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12038,ACC-2153562714,24,3712.56,9707.77,NaN,CUS-423725039,2018-10-24,Linda,F,-31.88,116.00,0.0,NaN,NaN,NaN,credit,posted,fe1b1a6bdd9b43f7985acc4af7b0a101,PAY/SALARY,20-30,2018,10,24,14,0,Wednesday,30,45169
12039,ACC-1217063613,27,4863.62,4863.86,NaN,CUS-1739931018,2018-09-26,Kimberly,F,-37.82,147.61,0.0,NaN,NaN,NaN,credit,posted,8659baa692924427aefbf4077c5a9d67,PAY/SALARY,20-30,2018,9,26,13,0,Wednesday,30,59174
12040,ACC-1217063613,27,4863.62,8905.77,NaN,CUS-1739931018,2018-10-26,Kimberly,F,-37.82,147.61,0.0,NaN,NaN,NaN,credit,posted,e6d8f31d269d4e8388e115719a59dd98,PAY/SALARY,20-30,2018,10,26,13,0,Friday,30,59174
12041,ACC-3100725361,25,6107.23,6111.57,NaN,CUS-2178051368,2018-09-26,Ronald,M,-17.03,145.73,0.0,NaN,NaN,NaN,credit,posted,7eb1fdb7aefb40d1a8ada1d27f556542,PAY/SALARY,20-30,2018,9,26,15,0,Wednesday,30,74305
12042,ACC-3100725361,25,6107.23,10753.02,NaN,CUS-2178051368,2018-10-26,Ronald,M,-17.03,145.73,0.0,NaN,NaN,NaN,credit,posted,56e1a0f55f354624a3c713c37415d216,PAY/SALARY,20-30,2018,10,26,15,0,Friday,30,74305

In [50]:
data.describe(include='all')

,account,age,amount,balance,card_present_flag,customer_id,date,first_name,gender,latitude,longitude,merchant_code,merchant_id,merchant_state,merchant_suburb,movement,status,transaction_id,txn_description,bin_age,year,month,day,hour,minute,dow,payment_period,annual_salary
count,12043,12043.000000,12043.000000,12043.000000,7717.000000,12043,12043,12043,12043,12043.000000,12043.000000,883.0,7717,7717,7717,12043,12043,12043,12043,12043,12043.0,12043.000000,12043.000000,12043.000000,12043.000000,12043,12043.000000,12043.000000
unique,100,NaN,NaN,NaN,NaN,100,91,80,2,NaN,NaN,NaN,5725,8,1609,2,2,12043,6,7,NaN,NaN,NaN,NaN,NaN,7,NaN,NaN
top,ACC-1598451071,NaN,NaN,NaN,NaN,CUS-2487424745,2018-09-28,Michael,M,NaN,NaN,NaN,106e1272-44ab-4dcb-a438-dd98e0071e51,NSW,Melbourne,debit,authorized,a623070bfead4541a6b0fff8a09e706c,SALES-POS,20-30,NaN,NaN,NaN,NaN,NaN,Friday,NaN,NaN
freq,578,NaN,NaN,NaN,NaN,578,174,746,6285,NaN,NaN,NaN,14,2169,255,11160,7717,1,3934,5071,NaN,NaN,NaN,NaN,NaN,2073,NaN,NaN
mean,NaN,30.582330,187.933588,14704.195553,0.802644,NaN,NaN,NaN,NaN,-38.164347,143.648563,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2018.0,9.011957,15.862908,13.268621,19.009632,NaN,11.470315,68652.099311
std,NaN,10.046343,592.599934,31503.722652,0.398029,NaN,NaN,NaN,NaN,54.622791,16.669352,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.816511,8.899598,5.777284,19.879112,NaN,7.049721,24300.863348
min,NaN,18.000000,0.100000,0.240000,0.000000,NaN,NaN,NaN,NaN,-573.000000,114.620000,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2018.0,8.000000,1.000000,0.000000,0.000000,NaN,0.000000,29875.000000
25%,NaN,22.000000,16.000000,3158.585000,1.000000,NaN,NaN,NaN,NaN,-37.700000,138.690000,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2018.0,8.000000,8.000000,9.000000,0.000000,NaN,7.000000,51650.000000
50%,NaN,28.000000,29.000000,6432.010000,1.000000,NaN,NaN,NaN,NaN,-33.890000,145.230000,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2018.0,9.000000,16.000000,13.000000,13.000000,NaN,14.000000,60494.000000
75%,NaN,38.000000,53.655000,12465.945000,1.000000,NaN,NaN,NaN,NaN,-30.750000,151.220000,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2018.0,10.000000,24.000000,18.000000,36.000000,NaN,14.000000,81701.000000
max,NaN,78.000000,8835.980000,267128.520000,1.000000,NaN,NaN,NaN,NaN,-12.370000,255.000000,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2018.0,10.000000,31.000000,23.000000,59.000000,NaN,61.000000,134946.000000

In [51]:
data["payment_period_mean_by_bin_age"] = data.groupby("bin_age")["payment_period"].transform("mean")
data["payment_period_max_by_bin_age"]  = data.groupby("bin_age")["payment_period"].transform("max")
# amount_mean_by_txn_description, amount_max_by_txn_description
data["amount_mean_by_txn_description"] = data.groupby("txn_description")["amount"].transform("mean")
data["amount_max_by_txn_description"]  = data.groupby("txn_description")["amount"].transform("max")

# balance_mean_by_merchant_suburb, balance_max_by_merchant_suburb
data["balance_mean_by_merchant_suburb"] = data.groupby("merchant_suburb")["balance"].transform("mean")
data["balance_max_by_merchant_suburb"]  = data.groupby("merchant_suburb")["balance"].transform("max")

In [52]:
data

,account,age,amount,balance,card_present_flag,customer_id,date,first_name,gender,latitude,longitude,merchant_code,merchant_id,merchant_state,merchant_suburb,movement,status,transaction_id,txn_description,bin_age,year,month,day,hour,minute,dow,payment_period,annual_salary,payment_period_mean_by_bin_age,payment_period_max_by_bin_age,amount_mean_by_txn_description,amount_max_by_txn_description,balance_mean_by_merchant_suburb,balance_max_by_merchant_suburb
0,ACC-1598451071,26,16.25,35.39,1.0,CUS-2487424745,2018-08-01,Diana,F,-27.95,153.41,NaN,81c48296-73be-44a7-befa-d053f48ce7cd,QLD,Ashmore,debit,authorized,a623070bfead4541a6b0fff8a09e706c,POS,20-30,2018,8,1,1,1,Wednesday,7,52856,13.650562,61,40.407412,7081.09,5340.941250,22315.43
1,ACC-1598451071,26,14.19,21.20,0.0,CUS-2487424745,2018-08-01,Diana,F,-27.95,153.41,NaN,830a451c-316e-4a6a-bf25-e37caedca49e,NSW,Sydney,debit,authorized,13270a2a902145da9db4c951e04b51b9,SALES-POS,20-30,2018,8,1,1,13,Wednesday,7,52856,13.650562,61,39.909789,4233.00,10934.540901,205177.72
2,ACC-1598451071,26,3.25,17.95,1.0,CUS-2487424745,2018-08-01,Diana,F,-27.95,153.41,NaN,b4e02c10-0852-4273-b8fd-7b3395e32eb0,QLD,Mermaid Beach,debit,authorized,329adf79878c4cf0aeb4188b4691c266,SALES-POS,20-30,2018,8,1,1,51,Wednesday,7,52856,13.650562,61,39.909789,4233.00,2391.202000,6808.64
3,ACC-1598451071,26,14.10,3.85,1.0,CUS-2487424745,2018-08-01,Diana,F,-27.95,153.41,NaN,f2ef6270-cf91-409f-a6a2-fbd6735ea500,NSW,Byron Bay,debit,authorized,1c12c9ad77894ef8b507fb091e41e928,POS,20-30,2018,8,1,8,9,Wednesday,7,52856,13.650562,61,40.407412,7081.09,595.520000,1085.52
4,ACC-1598451071,26,10.67,1006.85,1.0,CUS-2487424745,2018-08-01,Diana,F,-27.95,153.41,NaN,44abc19c-aa5c-40bd-b1d0-9b2f236189ea,QLD,Bundall,debit,authorized,cd0113426970425a8524e55f4079408f,POS,20-30,2018,8,1,18,19,Wednesday,7,52856,13.650562,61,40.407412,7081.09,2117.856000,4632.05
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12038,ACC-2153562714,24,3712.56,9707.77,NaN,CUS-423725039,2018-10-24,Linda,F,-31.88,116.00,0.0,NaN,NaN,NaN,credit,posted,fe1b1a6bdd9b43f7985acc4af7b0a101,PAY/SALARY,20-30,2018,10,24,14,0,Wednesday,30,45169,13.650562,61,1898.728029,8835.98,NaN,NaN
12039,ACC-1217063613,27,4863.62,4863.86,NaN,CUS-1739931018,2018-09-26,Kimberly,F,-37.82,147.61,0.0,NaN,NaN,NaN,credit,posted,8659baa692924427aefbf4077c5a9d67,PAY/SALARY,20-30,2018,9,26,13,0,Wednesday,30,59174,13.650562,61,1898.728029,8835.98,NaN,NaN
12040,ACC-1217063613,27,4863.62,8905.77,NaN,CUS-1739931018,2018-10-26,Kimberly,F,-37.82,147.61,0.0,NaN,NaN,NaN,credit,posted,e6d8f31d269d4e8388e115719a59dd98,PAY/SALARY,20-30,2018,10,26,13,0,Friday,30,59174,13.650562,61,1898.728029,8835.98,NaN,NaN
12041,ACC-3100725361,25,6107.23,6111.57,NaN,CUS-2178051368,2018-09-26,Ronald,M,-17.03,145.73,0.0,NaN,NaN,NaN,credit,posted,7eb1fdb7aefb40d1a8ada1d27f556542,PAY/SALARY,20-30,2018,9,26,15,0,Wednesday,30,74305,13.650562,61,1898.728029,8835.98,NaN,NaN
12042,ACC-3100725361,25,6107.23,10753.02,NaN,CUS-2178051368,2018-10-26,Ronald,M,-17.03,145.73,0.0,NaN,NaN,NaN,credit,posted,56e1a0f55f354624a3c713c37415d216,PAY/SALARY,20-30,2018,10,26,15,0,Friday,30,74305,13.650562,61,1898.728029,8835.98,NaN,NaN

In [53]:
data.columns

Index(['account', 'age', 'amount', 'balance', 'card_present_flag',
       'customer_id', 'date', 'first_name', 'gender', 'latitude', 'longitude',
       'merchant_code', 'merchant_id', 'merchant_state', 'merchant_suburb',
       'movement', 'status', 'transaction_id', 'txn_description', 'bin_age',
       'year', 'month', 'day', 'hour', 'minute', 'dow', 'payment_period',
       'annual_salary', 'payment_period_mean_by_bin_age',
       'payment_period_max_by_bin_age', 'amount_mean_by_txn_description',
       'amount_max_by_txn_description', 'balance_mean_by_merchant_suburb',
       'balance_max_by_merchant_suburb'],
      dtype='object')

In [54]:
data.drop(['account','customer_id','date', 'first_name','merchant_id','merchant_suburb','transaction_id'], axis=1, inplace=True)
data

,age,amount,balance,card_present_flag,gender,latitude,longitude,merchant_code,merchant_state,movement,status,txn_description,bin_age,year,month,day,hour,minute,dow,payment_period,annual_salary,payment_period_mean_by_bin_age,payment_period_max_by_bin_age,amount_mean_by_txn_description,amount_max_by_txn_description,balance_mean_by_merchant_suburb,balance_max_by_merchant_suburb
0,26,16.25,35.39,1.0,F,-27.95,153.41,NaN,QLD,debit,authorized,POS,20-30,2018,8,1,1,1,Wednesday,7,52856,13.650562,61,40.407412,7081.09,5340.941250,22315.43
1,26,14.19,21.20,0.0,F,-27.95,153.41,NaN,NSW,debit,authorized,SALES-POS,20-30,2018,8,1,1,13,Wednesday,7,52856,13.650562,61,39.909789,4233.00,10934.540901,205177.72
2,26,3.25,17.95,1.0,F,-27.95,153.41,NaN,QLD,debit,authorized,SALES-POS,20-30,2018,8,1,1,51,Wednesday,7,52856,13.650562,61,39.909789,4233.00,2391.202000,6808.64
3,26,14.10,3.85,1.0,F,-27.95,153.41,NaN,NSW,debit,authorized,POS,20-30,2018,8,1,8,9,Wednesday,7,52856,13.650562,61,40.407412,7081.09,595.520000,1085.52
4,26,10.67,1006.85,1.0,F,-27.95,153.41,NaN,QLD,debit,authorized,POS,20-30,2018,8,1,18,19,Wednesday,7,52856,13.650562,61,40.407412,7081.09,2117.856000,4632.05
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12038,24,3712.56,9707.77,NaN,F,-31.88,116.00,0.0,NaN,credit,posted,PAY/SALARY,20-30,2018,10,24,14,0,Wednesday,30,45169,13.650562,61,1898.728029,8835.98,NaN,NaN
12039,27,4863.62,4863.86,NaN,F,-37.82,147.61,0.0,NaN,credit,posted,PAY/SALARY,20-30,2018,9,26,13,0,Wednesday,30,59174,13.650562,61,1898.728029,8835.98,NaN,NaN
12040,27,4863.62,8905.77,NaN,F,-37.82,147.61,0.0,NaN,credit,posted,PAY/SALARY,20-30,2018,10,26,13,0,Friday,30,59174,13.650562,61,1898.728029,8835.98,NaN,NaN
12041,25,6107.23,6111.57,NaN,M,-17.03,145.73,0.0,NaN,credit,posted,PAY/SALARY,20-30,2018,9,26,15,0,Wednesday,30,74305,13.650562,61,1898.728029,8835.98,NaN,NaN
12042,25,6107.23,10753.02,NaN,M,-17.03,145.73,0.0,NaN,credit,posted,PAY/SALARY,20-30,2018,10,26,15,0,Friday,30,74305,13.650562,61,1898.728029,8835.98,NaN,NaN

In [55]:
pd.set_option('display.max_columns',None)
data.describe(include ='all')

,age,amount,balance,card_present_flag,gender,latitude,longitude,merchant_code,merchant_state,movement,status,txn_description,bin_age,year,month,day,hour,minute,dow,payment_period,annual_salary,payment_period_mean_by_bin_age,payment_period_max_by_bin_age,amount_mean_by_txn_description,amount_max_by_txn_description,balance_mean_by_merchant_suburb,balance_max_by_merchant_suburb
count,12043.000000,12043.000000,12043.000000,7717.000000,12043,12043.000000,12043.000000,883.0,7717,12043,12043,12043,12043,12043.0,12043.000000,12043.000000,12043.000000,12043.000000,12043,12043.000000,12043.000000,12043.000000,12043.000000,12043.000000,12043.000000,7717.000000,7717.000000
unique,NaN,NaN,NaN,NaN,2,NaN,NaN,NaN,8,2,2,6,7,NaN,NaN,NaN,NaN,NaN,7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
top,NaN,NaN,NaN,NaN,M,NaN,NaN,NaN,NSW,debit,authorized,SALES-POS,20-30,NaN,NaN,NaN,NaN,NaN,Friday,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
freq,NaN,NaN,NaN,NaN,6285,NaN,NaN,NaN,2169,11160,7717,3934,5071,NaN,NaN,NaN,NaN,NaN,2073,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
mean,30.582330,187.933588,14704.195553,0.802644,NaN,-38.164347,143.648563,0.0,NaN,NaN,NaN,NaN,NaN,2018.0,9.011957,15.862908,13.268621,19.009632,NaN,11.470315,68652.099311,11.470315,33.660301,187.933588,4819.233066,11871.056585,59225.017797
std,10.046343,592.599934,31503.722652,0.398029,NaN,54.622791,16.669352,0.0,NaN,NaN,NaN,NaN,NaN,0.0,0.816511,8.899598,5.777284,19.879112,NaN,7.049721,24300.863348,2.033555,23.336297,481.585450,2284.221028,14088.448192,78402.243162
min,18.000000,0.100000,0.240000,0.000000,NaN,-573.000000,114.620000,0.0,NaN,NaN,NaN,NaN,NaN,2018.0,8.000000,1.000000,0.000000,0.000000,NaN,0.000000,29875.000000,7.000000,7.000000,39.909789,1916.000000,6.480000,6.480000
25%,22.000000,16.000000,3158.585000,1.000000,NaN,-37.700000,138.690000,0.0,NaN,NaN,NaN,NaN,NaN,2018.0,8.000000,8.000000,9.000000,0.000000,NaN,7.000000,51650.000000,9.047577,14.000000,39.909789,1981.000000,5178.075000,10471.980000
50%,28.000000,29.000000,6432.010000,1.000000,NaN,-33.890000,145.230000,0.0,NaN,NaN,NaN,NaN,NaN,2018.0,9.000000,16.000000,13.000000,13.000000,NaN,14.000000,60494.000000,11.276875,14.000000,40.407412,4233.000000,8946.267500,21964.780000
75%,38.000000,53.655000,12465.945000,1.000000,NaN,-30.750000,151.220000,0.0,NaN,NaN,NaN,NaN,NaN,2018.0,10.000000,24.000000,18.000000,36.000000,NaN,14.000000,81701.000000,13.650562,61.000000,77.613077,7081.090000,13823.178431,60310.070000
max,78.000000,8835.980000,267128.520000,1.000000,NaN,-12.370000,255.000000,0.0,NaN,NaN,NaN,NaN,NaN,2018.0,10.000000,31.000000,23.000000,59.000000,NaN,61.000000,134946.000000,13.650562,61.000000,1898.728029,8835.980000,205624.020000,267093.660000

In [58]:
data.isnull().sum()

age                                    0
amount                                 0
balance                                0
card_present_flag                   4326
gender                                 0
latitude                               0
longitude                              0
merchant_code                      11160
merchant_state                      4326
movement                               0
status                                 0
txn_description                        0
bin_age                                0
year                                   0
month                                  0
day                                    0
hour                                   0
minute                                 0
dow                                    0
payment_period                         0
annual_salary                          0
payment_period_mean_by_bin_age         0
payment_period_max_by_bin_age          0
amount_mean_by_txn_description         0
amount_max_by_txn_description          0
balance_mean_by_merchant_suburb     4326
balance_max_by_merchant_suburb      4326
dtype: int64

In [59]:
for i in data.columns:
    if data[i].dtypes==object:
        print(i)

gender
merchant_state
movement
status
txn_description
bin_age
dow

In [62]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()

data["gender"] = le.fit_transform(data["gender"])
data["merchant_state"] = le.fit_transform(data["merchant_state"])
data['movement']=le.fit_transform(data['movement'])
data['status']=le.fit_transform(data['status'])
data['txn_description']=le.fit_transform(data['txn_description'])
data['bin_age']=le.fit_transform(data['bin_age'])
data['dow']=le.fit_transform(data['dow'])
                                        
data

,age,amount,balance,card_present_flag,gender,latitude,longitude,merchant_code,merchant_state,movement,status,txn_description,bin_age,year,month,day,hour,minute,dow,payment_period,annual_salary,payment_period_mean_by_bin_age,payment_period_max_by_bin_age,amount_mean_by_txn_description,amount_max_by_txn_description,balance_mean_by_merchant_suburb,balance_max_by_merchant_suburb
0,26,16.25,35.39,1.0,0,-27.95,153.41,NaN,3,1,0,4,0,2018,8,1,1,1,6,7,52856,13.650562,61,40.407412,7081.09,5340.941250,22315.43
1,26,14.19,21.20,0.0,0,-27.95,153.41,NaN,1,1,0,5,0,2018,8,1,1,13,6,7,52856,13.650562,61,39.909789,4233.00,10934.540901,205177.72
2,26,3.25,17.95,1.0,0,-27.95,153.41,NaN,3,1,0,5,0,2018,8,1,1,51,6,7,52856,13.650562,61,39.909789,4233.00,2391.202000,6808.64
3,26,14.10,3.85,1.0,0,-27.95,153.41,NaN,1,1,0,4,0,2018,8,1,8,9,6,7,52856,13.650562,61,40.407412,7081.09,595.520000,1085.52
4,26,10.67,1006.85,1.0,0,-27.95,153.41,NaN,3,1,0,4,0,2018,8,1,18,19,6,7,52856,13.650562,61,40.407412,7081.09,2117.856000,4632.05
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12038,24,3712.56,9707.77,NaN,0,-31.88,116.00,0.0,8,0,1,1,0,2018,10,24,14,0,6,30,45169,13.650562,61,1898.728029,8835.98,NaN,NaN
12039,27,4863.62,4863.86,NaN,0,-37.82,147.61,0.0,8,0,1,1,0,2018,9,26,13,0,6,30,59174,13.650562,61,1898.728029,8835.98,NaN,NaN
12040,27,4863.62,8905.77,NaN,0,-37.82,147.61,0.0,8,0,1,1,0,2018,10,26,13,0,0,30,59174,13.650562,61,1898.728029,8835.98,NaN,NaN
12041,25,6107.23,6111.57,NaN,1,-17.03,145.73,0.0,8,0,1,1,0,2018,9,26,15,0,6,30,74305,13.650562,61,1898.728029,8835.98,NaN,NaN
12042,25,6107.23,10753.02,NaN,1,-17.03,145.73,0.0,8,0,1,1,0,2018,10,26,15,0,0,30,74305,13.650562,61,1898.728029,8835.98,NaN,NaN

In [63]:
data.isnull().sum()

age                                    0
amount                                 0
balance                                0
card_present_flag                   4326
gender                                 0
latitude                               0
longitude                              0
merchant_code                      11160
merchant_state                         0
movement                               0
status                                 0
txn_description                        0
bin_age                                0
year                                   0
month                                  0
day                                    0
hour                                   0
minute                                 0
dow                                    0
payment_period                         0
annual_salary                          0
payment_period_mean_by_bin_age         0
payment_period_max_by_bin_age          0
amount_mean_by_txn_description         0
amount_max_by_txn_description          0
balance_mean_by_merchant_suburb     4326
balance_max_by_merchant_suburb      4326
dtype: int64

In [65]:
y = data['annual_salary']
x = data.drop('annual_salary', axis = 1)

In [66]:
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state = 42)

In [67]:
from sklearn import metrics

def evaluate(model,X_train, y_train, X_test, y_test):
    
    y_pred = model.predict(X_test)
    
    mae_test = metrics.mean_absolute_error(y_test, y_pred)
    mse_test = metrics.mean_squared_error(y_test, y_pred)
    rmse_test = np.sqrt(mse_test)
    r2_test = metrics.r2_score(y_test, y_pred)


    y_pred_train = model.predict(X_train)

    mae_train = metrics.mean_absolute_error(y_train, y_pred_train)
    mse_train = metrics.mean_squared_error(y_train, y_pred_train)
    rmse_train = np.sqrt(mse_train)
    r2_train = metrics.r2_score(y_train, y_pred_train)


    results_dict = {
        'Metric': ['MAE', 'MSE', 'RMSE', 'R2'],
        'Train': [mae_train, mse_train, rmse_train, r2_train*100],
        'Test': [mae_test, mse_test, rmse_test, r2_test*100]
    }

    results_df = pd.DataFrame(results_dict)
    
    return results_df

In [68]:
reg = RandomForestRegressor(random_state=42)
reg.fit(X_train, y_train)

RandomForestRegressor(random_state=42)

In [69]:
from sklearn.tree import export_text

one_tree = reg.estimators_[7]

tree_rules_rf = export_text(one_tree, feature_names=list(X_train.columns))
print(tree_rules_rf)

|--- balance <= 10161.72
|   |--- balance <= 6014.91
|   |   |--- month <= 8.50
|   |   |   |--- balance <= 3358.32
|   |   |   |   |--- longitude <= 153.03
|   |   |   |   |   |--- longitude <= 152.15
|   |   |   |   |   |   |--- latitude <= -34.19
|   |   |   |   |   |   |   |--- latitude <= -37.50
|   |   |   |   |   |   |   |   |--- latitude <= -40.43
|   |   |   |   |   |   |   |   |   |--- value: [30034.00]
|   |   |   |   |   |   |   |   |--- latitude >  -40.43
|   |   |   |   |   |   |   |   |   |--- latitude <= -37.84
|   |   |   |   |   |   |   |   |   |   |--- latitude <= -37.84
|   |   |   |   |   |   |   |   |   |   |   |--- truncated branch of depth 8
|   |   |   |   |   |   |   |   |   |   |--- latitude >  -37.84
|   |   |   |   |   |   |   |   |   |   |   |--- truncated branch of depth 2
|   |   |   |   |   |   |   |   |   |--- latitude >  -37.84
|   |   |   |   |   |   |   |   |   |   |--- latitude <= -37.83
|   |   |   |   |   |   |   |   |   |   |   |--- value: [36711.00]
|   |   |   |   |   |   |   |   |   |   |--- latitude >  -37.83
|   |   |   |   |   |   |   |   |   |   |   |--- truncated branch of depth 7
|   |   |   |   |   |   |   |--- latitude >  -37.50
|   |   |   |   |   |   |   |   |--- longitude <= 138.60
|   |   |   |   |   |   |   |   |   |--- value: [101500.00]
|   |   |   |   |   |   |   |   |--- longitude >  138.60
|   |   |   |   |   |   |   |   |   |--- gender <= 0.50
|   |   |   |   |   |   |   |   |   |   |--- payment_period <= 37.50
|   |   |   |   |   |   |   |   |   |   |   |--- truncated branch of depth 3
|   |   |   |   |   |   |   |   |   |   |--- payment_period >  37.50
|   |   |   |   |   |   |   |   |   |   |   |--- value: [29875.00]
|   |   |   |   |   |   |   |   |   |--- gender >  0.50
|   |   |   |   |   |   |   |   |   |   |--- payment_period_max_by_bin_age <= 37.50
|   |   |   |   |   |   |   |   |   |   |   |--- value: [60833.00]
|   |   |   |   |   |   |   |   |   |   |--- payment_period_max_by_bin_age >  37.50
|   |   |   |   |   |   |   |   |   |   |   |--- truncated branch of depth 2
|   |   |   |   |   |   |--- latitude >  -34.19
|   |   |   |   |   |   |   |--- latitude <= -33.95
|   |   |   |   |   |   |   |   |--- balance <= 2530.04
|   |   |   |   |   |   |   |   |   |--- payment_period <= 10.50
|   |   |   |   |   |   |   |   |   |   |--- value: [118904.00]
|   |   |   |   |   |   |   |   |   |--- payment_period >  10.50
|   |   |   |   |   |   |   |   |   |   |--- age <= 25.00
|   |   |   |   |   |   |   |   |   |   |   |--- value: [103698.00]
|   |   |   |   |   |   |   |   |   |   |--- age >  25.00
|   |   |   |   |   |   |   |   |   |   |   |--- value: [75256.00]
|   |   |   |   |   |   |   |   |--- balance >  2530.04
|   |   |   |   |   |   |   |   |   |--- value: [75256.00]
|   |   |   |   |   |   |   |--- latitude >  -33.95
|   |   |   |   |   |   |   |   |--- age <= 34.50
|   |   |   |   |   |   |   |   |   |--- age <= 32.50
|   |   |   |   |   |   |   |   |   |   |--- longitude <= 150.73
|   |   |   |   |   |   |   |   |   |   |   |--- truncated branch of depth 7
|   |   |   |   |   |   |   |   |   |   |--- longitude >  150.73
|   |   |   |   |   |   |   |   |   |   |   |--- truncated branch of depth 5
|   |   |   |   |   |   |   |   |   |--- age >  32.50
|   |   |   |   |   |   |   |   |   |   |--- longitude <= 140.97
|   |   |   |   |   |   |   |   |   |   |   |--- value: [91709.00]
|   |   |   |   |   |   |   |   |   |   |--- longitude >  140.97
|   |   |   |   |   |   |   |   |   |   |   |--- value: [89237.00]
|   |   |   |   |   |   |   |   |--- age >  34.50
|   |   |   |   |   |   |   |   |   |--- age <= 44.50
|   |   |   |   |   |   |   |   |   |   |--- latitude <= -33.86
|   |   |   |   |   |   |   |   |   |   |   |--- value: [52254.00]
|   |   |   |   |   |   |   |   |   |   |--- latitude >  -33.86
|   |   |   |   |   |   |   |   |   |   |   |--- truncated branch of depth 3
|   |   |   |   |   |   |   |   |   |--- age >  44.50
|   |   |   |   |   |   |   |   |   |   |--- payment_period <= 10.50
|   |   |   |   |   |   |   |   |   |   |   |--- value: [66350.00]
|   |   |   |   |   |   |   |   |   |   |--- payment_period >  10.50
|   |   |   |   |   |   |   |   |   |   |   |--- value: [98701.00]
|   |   |   |   |   |--- longitude >  152.15
|   |   |   |   |   |   |--- value: [132691.00]
|   |   |   |   |--- longitude >  153.03
|   |   |   |   |   |--- latitude <= -27.98
|   |   |   |   |   |   |--- longitude <= 204.21
|   |   |   |   |   |   |   |--- value: [107733.00]
|   |   |   |   |   |   |--- longitude >  204.21
|   |   |   |   |   |   |   |--- value: [86786.00]
|   |   |   |   |   |--- latitude >  -27.98
|   |   |   |   |   |   |--- bin_age <= 4.50
|   |   |   |   |   |   |   |--- latitude <= -27.94
|   |   |   |   |   |   |   |   |--- value: [52856.00]
|   |   |   |   |   |   |   |--- latitude >  -27.94
|   |   |   |   |   |   |   |   |--- latitude <= -27.56
|   |   |   |   |   |   |   |   |   |--- gender <= 0.50
|   |   |   |   |   |   |   |   |   |   |--- value: [46516.00]
|   |   |   |   |   |   |   |   |   |--- gender >  0.50
|   |   |   |   |   |   |   |   |   |   |--- payment_period_max_by_bin_age <= 37.50
|   |   |   |   |   |   |   |   |   |   |   |--- value: [47838.00]
|   |   |   |   |   |   |   |   |   |   |--- payment_period_max_by_bin_age >  37.50
|   |   |   |   |   |   |   |   |   |   |   |--- value: [48058.00]
|   |   |   |   |   |   |   |   |--- latitude >  -27.56
|   |   |   |   |   |   |   |   |   |--- value: [50603.00]
|   |   |   |   |   |   |--- bin_age >  4.50
|   |   |   |   |   |   |   |--- value: [40090.00]
|   |   |   |--- balance >  3358.32
|   |   |   |   |--- age <= 28.50
|   |   |   |   |   |--- longitude <= 150.59
|   |   |   |   |   |   |--- longitude <= 144.80
|   |   |   |   |   |   |   |--- payment_period <= 10.50
|   |   |   |   |   |   |   |   |--- age <= 26.50
|   |   |   |   |   |   |   |   |   |--- age <= 19.50
|   |   |   |   |   |   |   |   |   |   |--- value: [51650.00]
|   |   |   |   |   |   |   |   |   |--- age >  19.50
|   |   |   |   |   |   |   |   |   |   |--- longitude <= 115.18
|   |   |   |   |   |   |   |   |   |   |   |--- value: [54076.00]
|   |   |   |   |   |   |   |   |   |   |--- longitude >  115.18
|   |   |   |   |   |   |   |   |   |   |   |--- truncated branch of depth 3
|   |   |   |   |   |   |   |   |--- age >  26.50
|   |   |   |   |   |   |   |   |   |--- value: [72803.00]
|   |   |   |   |   |   |   |--- payment_period >  10.50
|   |   |   |   |   |   |   |   |--- payment_period <= 22.00
|   |   |   |   |   |   |   |   |   |--- latitude <= -22.13
|   |   |   |   |   |   |   |   |   |   |--- age <= 23.00
|   |   |   |   |   |   |   |   |   |   |   |--- truncated branch of depth 2
|   |   |   |   |   |   |   |   |   |   |--- age >  23.00
|   |   |   |   |   |   |   |   |   |   |   |--- truncated branch of depth 2
|   |   |   |   |   |   |   |   |   |--- latitude >  -22.13
|   |   |   |   |   |   |   |   |   |   |--- value: [60137.00]
|   |   |   |   |   |   |   |   |--- payment_period >  22.00
|   |   |   |   |   |   |   |   |   |--- value: [45169.00]
|   |   |   |   |   |   |--- longitude >  144.80
|   |   |   |   |   |   |   |--- age <= 23.50
|   |   |   |   |   |   |   |   |--- age <= 22.50
|   |   |   |   |   |   |   |   |   |--- age <= 19.50
|   |   |   |   |   |   |   |   |   |   |--- day <= 15.00
|   |   |   |   |   |   |   |   |   |   |   |--- value: [68822.00]
|   |   |   |   |   |   |   |   |   |   |--- day >  15.00
|   |   |   |   |   |   |   |   |   |   |   |--- value: [64797.00]
|   |   |   |   |   |   |   |   |   |--- age >  19.50
|   |   |   |   |   |   |   |   |   |   |--- latitude <= -37.87
|   |   |   |   |   |   |   |   |   |   |   |--- truncated branch of depth 3
|   |   |   |   |   |   |   |   |   |   |--- latitude >  -37.87
|   |   |   |   |   |   |   |   |   |   |   |--- value: [42779.00]
|   |   |   |   |   |   |   |   |--- age >  22.50
|   |   |   |   |   |   |   |   |   |--- value: [84809.00]
|   |   |   |   |   |   |   |--- age >  23.50
|   |   |   |   |   |   |   |   |--- latitude <= -37.55
|   |   |   |   |   |   |   |   |   |--- amount_mean_by_txn_description <= 988.17
|   |   |   |   |   |   |   |   |   |   |--- value: [36669.00]
|   |   |   |   |   |   |   |   |   |--- amount_mean_by_txn_description >  988.17
|   |   |   |   |   |   |   |   |   |   |--- value: [36711.00]
|   |   |   |   |   |   |   |   |--- latitude >  -37.55
|   |   |   |   |   |   |   |   |   |--- balance <= 5615.86
|   |   |   |   |   |   |   |   |   |   |--- gender <= 0.50
|   |   |   |   |   |   |   |   |   |   |   |--- value: [48008.00]
|   |   |   |   |   |   |   |   |   |   |--- gender >  0.50
|   |   |   |   |   |   |   |   |   |   |   |--- value: [49966.00]
|   |   |   |   |   |   |   |   |   |--- balance >  5615.86
|   |   |   |   |   |   |   |   |   |   |--- value: [59504.00]
|   |   |   |   |   |--- longitude >  150.59
|   |   |   |   |   |   |--- age <= 19.50
|   |   |   |   |   |   |   |--- gender <= 0.50
|   |   |   |   |   |   |   |   |--- value: [103698.00]
|   |   |   |   |   |   |   |--- gender >  0.50
|   |   |   |   |   |   |   |   |--- value: [107733.00]
|   |   |   |   |   |   |--- age >  19.50
|   |   |   |   |   |   |   |--- latitude <= -303.47
|   |   |   |   |   |   |   |   |--- value: [86786.00]
|   |   |   |   |   |   |   |--- latitude >  -303.47
|   |   |   |   |   |   |   |   |--- longitude <= 150.88
|   |   |   |   |   |   |   |   |   |--- value: [72765.00]
|   |   |   |   |   |   |   |   |--- longitude >  150.88
|   |   |   |   |   |   |   |   |   |--- payment_period_mean_by_bin_age <= 12.19
|   |   |   |   |   |   |   |   |   |   |--- value: [60494.00]
|   |   |   |   |   |   |   |   |   |--- payment_period_mean_by_bin_age >  12.19
|   |   |   |   |   |   |   |   |   |   |--- amount <= 1413.25
|   |   |   |   |   |   |   |   |   |   |   |--- truncated branch of depth 2
|   |   |   |   |   |   |   |   |   |   |--- amount >  1413.25
|   |   |   |   |   |   |   |   |   |   |   |--- value: [48053.00]
|   |   |   |   |--- age >  28.50
|   |   |   |   |   |--- day <= 21.50
|   |   |   |   |   |   |--- latitude <= -37.80
|   |   |   |   |   |   |   |--- age <= 39.00
|   |   |   |   |   |   |   |   |--- value: [127398.00]
|   |   |   |   |   |   |   |--- age >  39.00
|   |   |   |   |   |   |   |   |--- value: [134946.00]
|   |   |   |   |   |   |--- latitude >  -37.80
|   |   |   |   |   |   |   |--- balance <= 4939.28
|   |   |   |   |   |   |   |   |--- latitude <= -36.34
|   |   |   |   |   |   |   |   |   |--- day <= 15.50
|   |   |   |   |   |   |   |   |   |   |--- value: [75277.00]
|   |   |   |   |   |   |   |   |   |--- day >  15.50
|   |   |   |   |   |   |   |   |   |   |--- value: [54391.00]
|   |   |   |   |   |   |   |   |--- latitude >  -36.34
|   |   |   |   |   |   |   |   |   |--- longitude <= 150.43
|   |   |   |   |   |   |   |   |   |   |--- longitude <= 138.62
|   |   |   |   |   |   |   |   |   |   |   |--- truncated branch of depth 5
|   |   |   |   |   |   |   |   |   |   |--- longitude >  138.62
|   |   |   |   |   |   |   |   |   |   |   |--- truncated branch of depth 3
|   |   |   |   |   |   |   |   |   |--- longitude >  150.43
|   |   |   |   |   |   |   |   |   |   |--- age <= 34.50
|   |   |   |   |   |   |   |   |   |   |   |--- value: [89237.00]
|   |   |   |   |   |   |   |   |   |   |--- age >  34.50
|   |   |   |   |   |   |   |   |   |   |   |--- truncated branch of depth 3
|   |   |   |   |   |   |   |--- balance >  4939.28
|   |   |   |   |   |   |   |   |--- latitude <= -36.26
|   |   |   |   |   |   |   |   |   |--- value: [95148.00]
|   |   |   |   |   |   |   |   |--- latitude >  -36.26
|   |   |   |   |   |   |   |   |   |--- age <= 36.50
|   |   |   |   |   |   |   |   |   |   |--- value: [60190.00]
|   |   |   |   |   |   |   |   |   |--- age >  36.50
|   |   |   |   |   |   |   |   |   |   |--- value: [60833.00]
|   |   |   |   |   |--- day >  21.50
|   |   |   |   |   |   |--- latitude <= -34.42
|   |   |   |   |   |   |   |--- balance <= 5241.93
|   |   |   |   |   |   |   |   |--- latitude <= -34.85
|   |   |   |   |   |   |   |   |   |--- longitude <= 145.11
|   |   |   |   |   |   |   |   |   |   |--- age <= 53.50
|   |   |   |   |   |   |   |   |   |   |   |--- truncated branch of depth 2
|   |   |   |   |   |   |   |   |   |   |--- age >  53.50
|   |   |   |   |   |   |   |   |   |   |   |--- value: [54391.00]
|   |   |   |   |   |   |   |   |   |--- longitude >  145.11
|   |   |   |   |   |   |   |   |   |   |--- value: [31094.00]
|   |   |   |   |   |   |   |   |--- latitude >  -34.85
|   |   |   |   |   |   |   |   |   |--- value: [44997.00]
|   |   |   |   |   |   |   |--- balance >  5241.93
|   |   |   |   |   |   |   |   |--- value: [75277.00]
|   |   |   |   |   |   |--- latitude >  -34.42
|   |   |   |   |   |   |   |--- longitude <= 151.17
|   |   |   |   |   |   |   |   |--- age <= 35.50
|   |   |   |   |   |   |   |   |   |--- latitude <= -33.88
|   |   |   |   |   |   |   |   |   |   |--- value: [75256.00]
|   |   |   |   |   |   |   |   |   |--- latitude >  -33.88
|   |   |   |   |   |   |   |   |   |   |--- bin_age <= 0.50
|   |   |   |   |   |   |   |   |   |   |   |--- value: [85343.00]
|   |   |   |   |   |   |   |   |   |   |--- bin_age >  0.50
|   |   |   |   |   |   |   |   |   |   |   |--- truncated branch of depth 2
|   |   |   |   |   |   |   |   |--- age >  35.50
|   |   |   |   |   |   |   |   |   |--- longitude <= 132.46
|   |   |   |   |   |   |   |   |   |   |--- value: [66350.00]
|   |   |   |   |   |   |   |   |   |--- longitude >  132.46
|   |   |   |   |   |   |   |   |   |   |--- value: [47802.00]
|   |   |   |   |   |   |   |--- longitude >  151.17
|   |   |   |   |   |   |   |   |--- value: [118904.00]
|   |   |--- month >  8.50
|   |   |   |--- longitude <= 134.75
|   |   |   |   |--- payment_period_mean_by_bin_age <= 9.88
|   |   |   |   |   |--- value: [91709.00]
|   |   |   |   |--- payment_period_mean_by_bin_age >  9.88
|   |   |   |   |   |--- age <= 26.50
|   |   |   |   |   |   |--- payment_period <= 22.00
|   |   |   |   |   |   |   |--- longitude <= 115.18
|   |   |   |   |   |   |   |   |--- value: [54076.00]
|   |   |   |   |   |   |   |--- longitude >  115.18
|   |   |   |   |   |   |   |   |--- longitude <= 115.76
|   |   |   |   |   |   |   |   |   |--- value: [63892.00]
|   |   |   |   |   |   |   |   |--- longitude >  115.76
|   |   |   |   |   |   |   |   |   |--- age <= 23.50
|   |   |   |   |   |   |   |   |   |   |--- payment_period_mean_by_bin_age <= 12.19
|   |   |   |   |   |   |   |   |   |   |   |--- value: [59380.00]
|   |   |   |   |   |   |   |   |   |   |--- payment_period_mean_by_bin_age >  12.19
|   |   |   |   |   |   |   |   |   |   |   |--- value: [60137.00]
|   |   |   |   |   |   |   |   |   |--- age >  23.50
|   |   |   |   |   |   |   |   |   |   |--- value: [57300.00]
|   |   |   |   |   |   |--- payment_period >  22.00
|   |   |   |   |   |   |   |--- value: [45169.00]
|   |   |   |   |   |--- age >  26.50
|   |   |   |   |   |   |--- payment_period_mean_by_bin_age <= 12.46
|   |   |   |   |   |   |   |--- value: [66350.00]
|   |   |   |   |   |   |--- payment_period_mean_by_bin_age >  12.46
|   |   |   |   |   |   |   |--- value: [74047.00]
|   |   |   |--- longitude >  134.75
|   |   |   |   |--- latitude <= -307.94
|   |   |   |   |   |--- value: [86786.00]
|   |   |   |   |--- latitude >  -307.94
|   |   |   |   |   |--- latitude <= -22.26
|   |   |   |   |   |   |--- latitude <= -40.43
|   |   |   |   |   |   |   |--- value: [30034.00]
|   |   |   |   |   |   |--- latitude >  -40.43
|   |   |   |   |   |   |   |--- longitude <= 143.74
|   |   |   |   |   |   |   |   |--- payment_period_max_by_bin_age <= 37.50
|   |   |   |   |   |   |   |   |   |--- payment_period <= 3.50
|   |   |   |   |   |   |   |   |   |   |--- value: [60833.00]
|   |   |   |   |   |   |   |   |   |--- payment_period >  3.50
|   |   |   |   |   |   |   |   |   |   |--- latitude <= -34.86
|   |   |   |   |   |   |   |   |   |   |   |--- truncated branch of depth 2
|   |   |   |   |   |   |   |   |   |   |--- latitude >  -34.86
|   |   |   |   |   |   |   |   |   |   |   |--- value: [44997.00]
|   |   |   |   |   |   |   |   |--- payment_period_max_by_bin_age >  37.50
|   |   |   |   |   |   |   |   |   |--- value: [29875.00]
|   |   |   |   |   |   |   |--- longitude >  143.74
|   |   |   |   |   |   |   |   |--- payment_period <= 3.50
|   |   |   |   |   |   |   |   |   |--- value: [119082.00]
|   |   |   |   |   |   |   |   |--- payment_period >  3.50
|   |   |   |   |   |   |   |   |   |--- longitude <= 144.86
|   |   |   |   |   |   |   |   |   |   |--- payment_period_max_by_bin_age <= 37.50
|   |   |   |   |   |   |   |   |   |   |   |--- value: [75277.00]
|   |   |   |   |   |   |   |   |   |   |--- payment_period_max_by_bin_age >  37.50
|   |   |   |   |   |   |   |   |   |   |   |--- value: [72803.00]
|   |   |   |   |   |   |   |   |   |--- longitude >  144.86
|   |   |   |   |   |   |   |   |   |   |--- latitude <= -27.94
|   |   |   |   |   |   |   |   |   |   |   |--- truncated branch of depth 11
|   |   |   |   |   |   |   |   |   |   |--- latitude >  -27.94
|   |   |   |   |   |   |   |   |   |   |   |--- truncated branch of depth 5
|   |   |   |   |   |--- latitude >  -22.26
|   |   |   |   |   |   |--- value: [74305.00]
|   |--- balance >  6014.91
|   |   |--- month <= 8.50
|   |   |   |--- longitude <= 150.66
|   |   |   |   |--- age <= 39.50
|   |   |   |   |   |--- payment_period <= 10.50
|   |   |   |   |   |   |--- latitude <= -36.60
|   |   |   |   |   |   |   |--- value: [84809.00]
|   |   |   |   |   |   |--- latitude >  -36.60
|   |   |   |   |   |   |   |--- latitude <= -33.67
|   |   |   |   |   |   |   |   |--- value: [39855.00]
|   |   |   |   |   |   |   |--- latitude >  -33.67
|   |   |   |   |   |   |   |   |--- value: [51650.00]
|   |   |   |   |   |--- payment_period >  10.50
|   |   |   |   |   |   |--- balance <= 6940.71
|   |   |   |   |   |   |   |--- longitude <= 144.96
|   |   |   |   |   |   |   |   |--- longitude <= 141.76
|   |   |   |   |   |   |   |   |   |--- value: [29875.00]
|   |   |   |   |   |   |   |   |--- longitude >  141.76
|   |   |   |   |   |   |   |   |   |--- value: [36669.00]
|   |   |   |   |   |   |   |--- longitude >  144.96
|   |   |   |   |   |   |   |   |--- payment_period_mean_by_bin_age <= 9.88
|   |   |   |   |   |   |   |   |   |--- value: [80069.00]
|   |   |   |   |   |   |   |   |--- payment_period_mean_by_bin_age >  9.88
|   |   |   |   |   |   |   |   |   |--- day <= 20.00
|   |   |   |   |   |   |   |   |   |   |--- latitude <= -29.44
|   |   |   |   |   |   |   |   |   |   |   |--- value: [68822.00]
|   |   |   |   |   |   |   |   |   |   |--- latitude >  -29.44
|   |   |   |   |   |   |   |   |   |   |   |--- value: [66187.00]
|   |   |   |   |   |   |   |   |   |--- day >  20.00
|   |   |   |   |   |   |   |   |   |   |--- latitude <= -30.64
|   |   |   |   |   |   |   |   |   |   |   |--- value: [57845.00]
|   |   |   |   |   |   |   |   |   |   |--- latitude >  -30.64
|   |   |   |   |   |   |   |   |   |   |   |--- value: [59504.00]
|   |   |   |   |   |   |--- balance >  6940.71
|   |   |   |   |   |   |   |--- longitude <= 144.78
|   |   |   |   |   |   |   |   |--- latitude <= -31.28
|   |   |   |   |   |   |   |   |   |--- bin_age <= 0.50
|   |   |   |   |   |   |   |   |   |   |--- value: [93301.00]
|   |   |   |   |   |   |   |   |   |--- bin_age >  0.50
|   |   |   |   |   |   |   |   |   |   |--- day <= 22.50
|   |   |   |   |   |   |   |   |   |   |   |--- value: [95148.00]
|   |   |   |   |   |   |   |   |   |   |--- day >  22.50
|   |   |   |   |   |   |   |   |   |   |   |--- value: [95863.00]
|   |   |   |   |   |   |   |   |--- latitude >  -31.28
|   |   |   |   |   |   |   |   |   |--- value: [114852.00]

In [70]:
evaluate(reg, X_train, y_train, X_test, y_test)

  Metric          Train          Test
0    MAE     218.379361  5.203278e+02
1    MSE  833203.125285  3.685421e+06
2   RMSE     912.799609  1.919745e+03
3     R2      99.859066  9.937253e+01

In [71]:
def plot_feature_importances(model, feature_names):
    
    importances = model.feature_importances_
    
    importance_df = pd.DataFrame({
        'Feature': feature_names,
        'Importance': importances
    }).sort_values(by="Importance", ascending=False)
   
    
    #plt.figure(figsize=(10, 6))
    #plt.barh(importance_df['Feature'], importance_df['Importance'])
    #plt.title("Feature Importances")
    #plt.xlabel("Importance Score")
    #plt.ylabel("Feature")
    #plt.gca().invert_yaxis() 
    #plt.show()
    
    return importance_df

In [72]:
feature_names = X_train.columns

feature_importance_df = plot_feature_importances(reg, feature_names)

feature_importance_df

                            Feature  Importance
2                           balance    0.333933
5                          latitude    0.175929
6                         longitude    0.158466
0                               age    0.128873
19                   payment_period    0.065710
14                            month    0.054042
20   payment_period_mean_by_bin_age    0.036019
15                              day    0.013718
4                            gender    0.009743
12                          bin_age    0.008556
21    payment_period_max_by_bin_age    0.005468
1                            amount    0.002070
16                             hour    0.001675
23    amount_max_by_txn_description    0.001412
25   balance_max_by_merchant_suburb    0.000957
24  balance_mean_by_merchant_suburb    0.000890
8                    merchant_state    0.000751
18                              dow    0.000675
17                           minute    0.000334
11                  txn_description    0.000329
22   amount_mean_by_txn_description    0.000236
3                 card_present_flag    0.000108
10                           status    0.000053
9                          movement    0.000052
7                     merchant_code    0.000000
13                             year    0.000000

In [74]:
feature_importance_df.Feature.tolist()

['balance',
 'latitude',
 'longitude',
 'age',
 'payment_period',
 'month',
 'payment_period_mean_by_bin_age',
 'day',
 'gender',
 'bin_age',
 'payment_period_max_by_bin_age',
 'amount',
 'hour',
 'amount_max_by_txn_description',
 'balance_max_by_merchant_suburb',
 'balance_mean_by_merchant_suburb',
 'merchant_state',
 'dow',
 'minute',
 'txn_description',
 'amount_mean_by_txn_description',
 'card_present_flag',
 'status',
 'movement',
 'merchant_code',
 'year']

In [77]:
reg_selected = RandomForestRegressor(random_state=42)

reg_selected.fit(X_train[['balance',
	'latitude',	
	'longitude',	
	'age',	
	'payment_period',	
	'month',	
	'payment_period_mean_by_bin_age',
	'day']],y_train)

RandomForestRegressor(random_state=42)

In [78]:
evaluate(reg_selected,X_train[['balance',
	'latitude',	
	'longitude',	
	'age',	
	'payment_period',	
	'month',	
	'payment_period_mean_by_bin_age',
	'day']],y_train, 
         X_test[['balance',
	'latitude',	
	'longitude',	
	'age',	
	'payment_period',	
	'month',	
	'payment_period_mean_by_bin_age',
	'day']], y_test)

  Metric          Train          Test
0    MAE     134.377082  3.195498e+02
1    MSE  532466.699397  2.413914e+06
2   RMSE     729.703158  1.553678e+03
3     R2      99.909935  9.958902e+01

In [79]:
from sklearn.model_selection import RandomizedSearchCV

n_estimators = [int(x) for x in np.linspace(start = 200, stop = 1000, num = 10)]
max_depth = [int(x) for x in np.linspace(10, 100, num = 11)]

# Create the random grid
random_grid = {'n_estimators': n_estimators, # Number of trees in random forest
               'max_features': ['sqrt', 0.3, 0.5, None], # Number of features to consider at every split
               'max_depth': max_depth, # Maximum number of levels in tree
               'min_samples_split': [20,50], # Minimum number of samples required to split a node
               'min_samples_leaf': [5, 8, 10]} # Minimum number of samples required at each leaf node

In [81]:
rf_random = RandomizedSearchCV(estimator = reg, param_distributions = random_grid, n_iter = 10, cv = 3, verbose=1, random_state=42, n_jobs = -1)
# Fit the random search model
rf_random.fit(X_train[['balance',
	'latitude',	
	'longitude',	
	'age',	
	'payment_period',	
	'month',	
	'payment_period_mean_by_bin_age',
	'day']], y_train)

Fitting 3 folds for each of 10 candidates, totalling 30 fits

RandomizedSearchCV(cv=3, estimator=RandomForestRegressor(random_state=42),
                   n_jobs=-1,
                   param_distributions={'max_depth': [10, 19, 28, 37, 46, 55,
                                                      64, 73, 82, 91, 100],
                                        'max_features': ['sqrt', 0.3, 0.5,
                                                         None],
                                        'min_samples_leaf': [5, 8, 10],
                                        'min_samples_split': [20, 50],
                                        'n_estimators': [200, 288, 377, 466,
                                                         555, 644, 733, 822,
                                                         911, 1000]},
                   random_state=42, verbose=1)

In [82]:
rf_random.best_params_

{'n_estimators': 1000,
 'min_samples_split': 20,
 'min_samples_leaf': 5,
 'max_features': 'sqrt',
 'max_depth': 91}

In [106]:
optimized_model = rf_random.best_estimator_

evaluate(optimized_model, X_train[['balance',
	'latitude',	
	'longitude',	
	'age',	
	'payment_period',	
	'month',	
	'payment_period_mean_by_bin_age',
	'day']],y_train, 
  X_test[['balance',
	'latitude',	
	'longitude',	
	'age',	
	'payment_period',	
	'month',	
	'payment_period_mean_by_bin_age',
	'day']], y_test)

  Metric         Train          Test
0    MAE  1.043319e+03  1.253666e+03
1    MSE  4.746910e+06  6.452051e+06
2   RMSE  2.178740e+03  2.540089e+03
3     R2  9.919707e+01  9.890150e+01

In [84]:
from sklearn.tree import export_text

one_tree = optimized_model.estimators_[7]

tree_rules_rf = export_text(one_tree, feature_names=list(X_train[['balance',
	'latitude',	
	'longitude',	
	'age',	
	'payment_period',	
	'month',	
	'payment_period_mean_by_bin_age',
	'day']]))

print(tree_rules_rf)

|--- balance <= 10161.72
|   |--- latitude <= -12.41
|   |   |--- balance <= 6014.91
|   |   |   |--- payment_period <= 45.50
|   |   |   |   |--- latitude <= -307.94
|   |   |   |   |   |--- value: [86786.00]
|   |   |   |   |--- latitude >  -307.94
|   |   |   |   |   |--- balance <= 3839.44
|   |   |   |   |   |   |--- month <= 8.50
|   |   |   |   |   |   |   |--- latitude <= -27.98
|   |   |   |   |   |   |   |   |--- day <= 7.50
|   |   |   |   |   |   |   |   |   |--- latitude <= -28.40
|   |   |   |   |   |   |   |   |   |   |--- longitude <= 151.22
|   |   |   |   |   |   |   |   |   |   |   |--- truncated branch of depth 8
|   |   |   |   |   |   |   |   |   |   |--- longitude >  151.22
|   |   |   |   |   |   |   |   |   |   |   |--- value: [99923.33]
|   |   |   |   |   |   |   |   |   |--- latitude >  -28.40
|   |   |   |   |   |   |   |   |   |   |--- value: [107733.00]
|   |   |   |   |   |   |   |   |--- day >  7.50
|   |   |   |   |   |   |   |   |   |--- latitude <= -28.40
|   |   |   |   |   |   |   |   |   |   |--- latitude <= -40.43
|   |   |   |   |   |   |   |   |   |   |   |--- value: [30034.00]
|   |   |   |   |   |   |   |   |   |   |--- latitude >  -40.43
|   |   |   |   |   |   |   |   |   |   |   |--- truncated branch of depth 9
|   |   |   |   |   |   |   |   |   |--- latitude >  -28.40
|   |   |   |   |   |   |   |   |   |   |--- value: [107733.00]
|   |   |   |   |   |   |   |--- latitude >  -27.98
|   |   |   |   |   |   |   |   |--- age <= 36.00
|   |   |   |   |   |   |   |   |   |--- latitude <= -20.22
|   |   |   |   |   |   |   |   |   |   |--- latitude <= -27.64
|   |   |   |   |   |   |   |   |   |   |   |--- truncated branch of depth 4
|   |   |   |   |   |   |   |   |   |   |--- latitude >  -27.64
|   |   |   |   |   |   |   |   |   |   |   |--- truncated branch of depth 3
|   |   |   |   |   |   |   |   |   |--- latitude >  -20.22
|   |   |   |   |   |   |   |   |   |   |--- latitude <= -14.74
|   |   |   |   |   |   |   |   |   |   |   |--- value: [74305.00]
|   |   |   |   |   |   |   |   |   |   |--- latitude >  -14.74
|   |   |   |   |   |   |   |   |   |   |   |--- value: [60137.00]
|   |   |   |   |   |   |   |   |--- age >  36.00
|   |   |   |   |   |   |   |   |   |--- longitude <= 153.07
|   |   |   |   |   |   |   |   |   |   |--- payment_period_mean_by_bin_age <= 9.82
|   |   |   |   |   |   |   |   |   |   |   |--- value: [47802.00]
|   |   |   |   |   |   |   |   |   |   |--- payment_period_mean_by_bin_age >  9.82
|   |   |   |   |   |   |   |   |   |   |   |--- value: [50603.00]
|   |   |   |   |   |   |   |   |   |--- longitude >  153.07
|   |   |   |   |   |   |   |   |   |   |--- balance <= 1084.92
|   |   |   |   |   |   |   |   |   |   |   |--- value: [47838.00]
|   |   |   |   |   |   |   |   |   |   |--- balance >  1084.92
|   |   |   |   |   |   |   |   |   |   |   |--- truncated branch of depth 2
|   |   |   |   |   |   |--- month >  8.50
|   |   |   |   |   |   |   |--- latitude <= -40.40
|   |   |   |   |   |   |   |   |--- value: [30034.00]
|   |   |   |   |   |   |   |--- latitude >  -40.40
|   |   |   |   |   |   |   |   |--- latitude <= -22.26
|   |   |   |   |   |   |   |   |   |--- latitude <= -27.49
|   |   |   |   |   |   |   |   |   |   |--- day <= 6.50
|   |   |   |   |   |   |   |   |   |   |   |--- truncated branch of depth 9
|   |   |   |   |   |   |   |   |   |   |--- day >  6.50
|   |   |   |   |   |   |   |   |   |   |   |--- truncated branch of depth 11
|   |   |   |   |   |   |   |   |   |--- latitude >  -27.49
|   |   |   |   |   |   |   |   |   |   |--- value: [40090.00]
|   |   |   |   |   |   |   |   |--- latitude >  -22.26
|   |   |   |   |   |   |   |   |   |--- age <= 23.00
|   |   |   |   |   |   |   |   |   |   |--- value: [60137.00]
|   |   |   |   |   |   |   |   |   |--- age >  23.00
|   |   |   |   |   |   |   |   |   |   |--- value: [74305.00]
|   |   |   |   |   |--- balance >  3839.44
|   |   |   |   |   |   |--- payment_period <= 3.50
|   |   |   |   |   |   |   |--- age <= 38.50
|   |   |   |   |   |   |   |   |--- value: [60833.00]
|   |   |   |   |   |   |   |--- age >  38.50
|   |   |   |   |   |   |   |   |--- value: [119082.00]
|   |   |   |   |   |   |--- payment_period >  3.50
|   |   |   |   |   |   |   |--- month <= 8.50
|   |   |   |   |   |   |   |   |--- age <= 28.50
|   |   |   |   |   |   |   |   |   |--- age <= 23.50
|   |   |   |   |   |   |   |   |   |   |--- longitude <= 148.81
|   |   |   |   |   |   |   |   |   |   |   |--- truncated branch of depth 7
|   |   |   |   |   |   |   |   |   |   |--- longitude >  148.81
|   |   |   |   |   |   |   |   |   |   |   |--- truncated branch of depth 3
|   |   |   |   |   |   |   |   |   |--- age >  23.50
|   |   |   |   |   |   |   |   |   |   |--- age <= 26.50
|   |   |   |   |   |   |   |   |   |   |   |--- truncated branch of depth 2
|   |   |   |   |   |   |   |   |   |   |--- age >  26.50
|   |   |   |   |   |   |   |   |   |   |   |--- value: [69385.91]
|   |   |   |   |   |   |   |   |--- age >  28.50
|   |   |   |   |   |   |   |   |   |--- longitude <= 145.10
|   |   |   |   |   |   |   |   |   |   |--- payment_period_mean_by_bin_age <= 8.02
|   |   |   |   |   |   |   |   |   |   |   |--- value: [54391.00]
|   |   |   |   |   |   |   |   |   |   |--- payment_period_mean_by_bin_age >  8.02
|   |   |   |   |   |   |   |   |   |   |   |--- truncated branch of depth 2
|   |   |   |   |   |   |   |   |   |--- longitude >  145.10
|   |   |   |   |   |   |   |   |   |   |--- payment_period <= 10.50
|   |   |   |   |   |   |   |   |   |   |   |--- truncated branch of depth 4
|   |   |   |   |   |   |   |   |   |   |--- payment_period >  10.50
|   |   |   |   |   |   |   |   |   |   |   |--- value: [62848.71]
|   |   |   |   |   |   |   |--- month >  8.50
|   |   |   |   |   |   |   |   |--- payment_period <= 22.00
|   |   |   |   |   |   |   |   |   |--- age <= 34.50
|   |   |   |   |   |   |   |   |   |   |--- longitude <= 134.72
|   |   |   |   |   |   |   |   |   |   |   |--- truncated branch of depth 4
|   |   |   |   |   |   |   |   |   |   |--- longitude >  134.72
|   |   |   |   |   |   |   |   |   |   |   |--- truncated branch of depth 11
|   |   |   |   |   |   |   |   |   |--- age >  34.50
|   |   |   |   |   |   |   |   |   |   |--- payment_period_mean_by_bin_age <= 9.82
|   |   |   |   |   |   |   |   |   |   |   |--- truncated branch of depth 4
|   |   |   |   |   |   |   |   |   |   |--- payment_period_mean_by_bin_age >  9.82
|   |   |   |   |   |   |   |   |   |   |   |--- truncated branch of depth 5
|   |   |   |   |   |   |   |   |--- payment_period >  22.00
|   |   |   |   |   |   |   |   |   |--- latitude <= -24.45
|   |   |   |   |   |   |   |   |   |   |--- value: [58507.10]
|   |   |   |   |   |   |   |   |   |--- latitude >  -24.45
|   |   |   |   |   |   |   |   |   |   |--- value: [74305.00]
|   |   |   |--- payment_period >  45.50
|   |   |   |   |--- value: [29875.00]
|   |   |--- balance >  6014.91
|   |   |   |--- payment_period_mean_by_bin_age <= 10.66
|   |   |   |   |--- longitude <= 150.83
|   |   |   |   |   |--- latitude <= -26.51
|   |   |   |   |   |   |--- month <= 9.50
|   |   |   |   |   |   |   |--- latitude <= -37.71
|   |   |   |   |   |   |   |   |--- payment_period_mean_by_bin_age <= 8.02
|   |   |   |   |   |   |   |   |   |--- value: [54391.00]
|   |   |   |   |   |   |   |   |--- payment_period_mean_by_bin_age >  8.02
|   |   |   |   |   |   |   |   |   |--- value: [80069.00]
|   |   |   |   |   |   |   |--- latitude >  -37.71
|   |   |   |   |   |   |   |   |--- longitude <= 138.62
|   |   |   |   |   |   |   |   |   |--- age <= 46.00
|   |   |   |   |   |   |   |   |   |   |--- value: [101500.00]
|   |   |   |   |   |   |   |   |   |--- age >  46.00
|   |   |   |   |   |   |   |   |   |   |--- value: [98701.00]
|   |   |   |   |   |   |   |   |--- longitude >  138.62
|   |   |   |   |   |   |   |   |   |--- value: [77304.20]
|   |   |   |   |   |   |--- month >  9.50
|   |   |   |   |   |   |   |--- balance <= 6810.86
|   |   |   |   |   |   |   |   |--- value: [39016.17]
|   |   |   |   |   |   |   |--- balance >  6810.86
|   |   |   |   |   |   |   |   |--- latitude <= -36.31
|   |   |   |   |   |   |   |   |   |--- value: [54391.00]
|   |   |   |   |   |   |   |   |--- latitude >  -36.31
|   |   |   |   |   |   |   |   |   |--- value: [60833.00]
|   |   |   |   |   |--- latitude >  -26.51
|   |   |   |   |   |   |--- value: [47802.00]
|   |   |   |   |--- longitude >  150.83
|   |   |   |   |   |--- payment_period <= 10.50
|   |   |   |   |   |   |--- longitude <= 153.03
|   |   |   |   |   |   |   |--- payment_period <= 3.50
|   |   |   |   |   |   |   |   |--- value: [119082.00]
|   |   |   |   |   |   |   |--- payment_period >  3.50
|   |   |   |   |   |   |   |   |--- age <= 34.50
|   |   |   |   |   |   |   |   |   |--- value: [89237.00]
|   |   |   |   |   |   |   |   |--- age >  34.50
|   |   |   |   |   |   |   |   |   |--- value: [127176.20]
|   |   |   |   |   |   |--- longitude >  153.03
|   |   |   |   |   |   |   |--- value: [50603.00]
|   |   |   |   |   |--- payment_period >  10.50
|   |   |   |   |   |   |--- latitude <= -33.49
|   |   |   |   |   |   |   |--- value: [75256.00]
|   |   |   |   |   |   |--- latitude >  -33.49
|   |   |   |   |   |   |   |--- value: [60190.00]
|   |   |   |--- payment_period_mean_by_bin_age >  10.66
|   |   |   |   |--- payment_period <= 10.50
|   |   |   |   |   |--- age <= 19.50
|   |   |   |   |   |   |--- longitude <= 127.30
|   |   |   |   |   |   |   |--- value: [51650.00]
|   |   |   |   |   |   |--- longitude >  127.30
|   |   |   |   |   |   |   |--- value: [39698.00]
|   |   |   |   |   |--- age >  19.50
|   |   |   |   |   |   |--- day <= 11.50
|   |   |   |   |   |   |   |--- month <= 8.50
|   |   |   |   |   |   |   |   |--- value: [39855.00]
|   |   |   |   |   |   |   |--- month >  8.50
|   |   |   |   |   |   |   |   |--- age <= 43.50
|   |   |   |   |   |   |   |   |   |--- day <= 7.50
|   |   |   |   |   |   |   |   |   |   |--- longitude <= 149.43
|   |   |   |   |   |   |   |   |   |   |   |--- truncated branch of depth 4
|   |   |   |   |   |   |   |   |   |   |--- longitude >  149.43
|   |   |   |   |   |   |   |   |   |   |   |--- value: [71988.57]
|   |   |   |   |   |   |   |   |   |--- day >  7.50
|   |   |   |   |   |   |   |   |   |   |--- balance <= 8200.66
|   |   |   |   |   |   |   |   |   |   |   |--- truncated branch of depth 2
|   |   |   |   |   |   |   |   |   |   |--- balance >  8200.66
|   |   |   |   |   |   |   |   |   |   |   |--- value: [72717.60]
|   |   |   |   |   |   |   |   |--- age >  43.50
|   |   |   |   |   |   |   |   |   |--- value: [39908.00]
|   |   |   |   |   |   |--- day >  11.50
|   |   |   |   |   |   |   |--- longitude <= 145.10
|   |   |   |   |   |   |   |   |--- payment_period <= 3.50
|   |   |   |   |   |   |   |   |   |--- value: [39855.00]
|   |   |   |   |   |   |   |   |--- payment_period >  3.50
|   |   |   |   |   |   |   |   |   |--- month <= 9.50
|   |   |   |   |   |   |   |   |   |   |--- latitude <= -34.74
|   |   |   |   |   |   |   |   |   |   |   |--- truncated branch of depth 2
|   |   |   |   |   |   |   |   |   |   |--- latitude >  -34.74
|   |   |   |   |   |   |   |   |   |   |   |--- truncated branch of depth 2
|   |   |   |   |   |   |   |   |   |--- month >  9.50
|   |   |   |   |   |   |   |   |   |   |--- day <= 25.50
|   |   |   |   |   |   |   |   |   |   |   |--- truncated branch of depth 6
|   |   |   |   |   |   |   |   |   |   |--- day >  25.50
|   |   |   |   |   |   |   |   |   |   |   |--- truncated branch of depth 3
|   |   |   |   |   |   |   |--- longitude >  145.10
|   |   |   |   |   |   |   |   |--- latitude <= -37.79
|   |   |   |   |   |   |   |   |   |--- value: [111343.27]
|   |   |   |   |   |   |   |   |--- latitude >  -37.79
|   |   |   |   |   |   |   |   |   |--- balance <= 8796.45
|   |   |   |   |   |   |   |   |   |   |--- longitude <= 150.79
|   |   |   |   |   |   |   |   |   |   |   |--- truncated branch of depth 2
|   |   |   |   |   |   |   |   |   |   |--- longitude >  150.79
|   |   |   |   |   |   |   |   |   |   |   |--- value: [51257.32]
|   |   |   |   |   |   |   |   |   |--- balance >  8796.45
|   |   |   |   |   |   |   |   |   |   |--- value: [75210.72]
|   |   |   |   |--- payment_period >  10.50
|   |   |   |   |   |--- longitude <= 151.25
|   |   |   |   |   |   |--- age <= 19.50
|   |   |   |   |   |   |   |--- balance <= 6693.04
|   |   |   |   |   |   |   |   |--- value: [56873.33]
|   |   |   |   |   |   |   |--- balance >  6693.04
|   |   |   |   |   |   |   |   |--- month <= 9.50
|   |   |   |   |   |   |   |   |   |--- day <= 23.50
|   |   |   |   |   |   |   |   |   |   |--- latitude <= -35.02
|   |   |   |   |   |   |   |   |   |   |   |--- value: [80179.65]
|   |   |   |   |   |   |   |   |   |   |--- latitude >  -35.02
|   |   |   |   |   |   |   |   |   |   |   |--- value: [103698.00]
|   |   |   |   |   |   |   |   |   |--- day >  23.50
|   |   |   |   |   |   |   |   |   |   |--- value: [84878.78]
|   |   |   |   |   |   |   |   |--- month >  9.50
|   |   |   |   |   |   |   |   |   |--- value: [63334.05]
|   |   |   |   |   |   |--- age >  19.50
|   |   |   |   |   |   |   |--- age <= 43.50
|   |   |   |   |   |   |   |   |--- payment_period <= 22.00
|   |   |   |   |   |   |   |   |   |--- payment_period_mean_by_bin_age <= 12.46
|   |   |   |   |   |   |   |   |   |   |--- latitude <= -37.83
|   |   |   |   |   |   |   |   |   |   |   |--- value: [42779.00]
|   |   |   |   |   |   |   |   |   |   |--- latitude >  -37.83
|   |   |   |   |   |   |   |   |   |   |   |--- truncated branch of depth 4
|   |   |   |   |   |   |   |   |   |--- payment_period_mean_by_bin_age >  12.46
|   |   |   |   |   |   |   |   |   |   |--- latitude <= -32.97
|   |   |   |   |   |   |   |   |   |   |   |--- truncated branch of depth 6
|   |   |   |   |   |   |   |   |   |   |--- latitude >  -32.97
|   |   |   |   |   |   |   |   |   |   |   |--- truncated branch of depth 5
|   |   |   |   |   |   |   |   |--- payment_period >  22.00
|   |   |   |   |   |   |   |   |   |--- payment_period <= 45.50
|   |   |   |   |   |   |   |   |   |   |--- balance <= 6167.68
|   |   |   |   |   |   |   |   |   |   |   |--- value: [62650.60]
|   |   |   |   |   |   |   |   |   |   |--- balance >  6167.68
|   |   |   |   |   |   |   |   |   |   |   |--- value: [46206.41]
|   |   |   |   |   |   |   |   |   |--- payment_period >  45.50
|   |   |   |   |   |   |   |   |   |   |--- value: [29875.00]
|   |   |   |   |   |   |   |--- age >  43.50
|   |   |   |   |   |   |   |   |--- value: [75277.00]
|   |   |   |   |   |--- longitude >  151.25
|   |   |   |   |   |   |--- age <= 24.50
|   |   |   |   |   |   |   |--- longitude <= 204.21
|   |   |   |   |   |   |   |   |--- longitude <= 152.34
|   |   |   |   |   |   |   |   |   |--- value: [101782.00]
|   |   |   |   |   |   |   |   |--- longitude >  152.34
|   |   |   |   |   |   |   |   |   |--- value: [107733.00]
|   |   |   |   |   |   |   |--- longitude >  204.21
|   |   |   |   |   |   |   |   |--- value: [86786.00]
|   |   |   |   |   |   |--- age >  24.50
|   |   |   |   |   |   |   |--- value: [48053.00]
|   |--- latitude >  -12.41
|   |   |--- value: [91709.00]
|--- balance >  10161.72
|   |--- latitude <= -37.67
|   |   |--- balance <= 18204.38
|   |   |   |--- payment_period <= 10.50
|   |   |   |   |--- payment_period_mean_by_bin_age <= 12.46
|   |   |   |   |   |--- day <= 26.50
|   |   |   |   |   |   |--- age <= 39.00
|   |   |   |   |   |   |   |--- value: [127398.00]
|   |   |   |   |   |   |--- age >  39.00
|   |   |   |   |   |   |   |--- day <= 23.00
|   |   |   |   |   |   |   |   |--- value: [134946.00]
|   |   |   |   |   |   |   |--- day >  23.00
|   |   |   |   |   |   |   |   |--- value: [126890.50]
|   |   |   |   |   |--- day >  26.50
|   |   |   |   |   |   |--- value: [74529.75]
|   |   |   |   |--- payment_period_mean_by_bin_age >  12.46
|   |   |   |   |   |--- value: [84809.00]
|   |   |   |--- payment_period >  10.50
|   |   |   |   |--- balance <= 13276.54
|   |   |   |   |   |--- payment_period_mean_by_bin_age <= 12.46
|   |   |   |   |   |   |--- payment_period_mean_by_bin_age <= 11.00
|   |   |   |   |   |   |   |--- latitude <= -37.80
|   |   |   |   |   |   |   |   |--- value: [84205.52]
|   |   |   |   |   |   |   |--- latitude >  -37.80
|   |   |   |   |   |   |   |   |--- value: [64797.00]
|   |   |   |   |   |   |--- payment_period_mean_by_bin_age >  11.00
|   |   |   |   |   |   |   |--- value: [75277.00]
|   |   |   |   |   |--- payment_period_mean_by_bin_age >  12.46
|   |   |   |   |   |   |--- balance <= 11504.48
|   |   |   |   |   |   |   |--- latitude <= -37.78
|   |   |   |   |   |   |   |   |--- value: [57167.00]
|   |   |   |   |   |   |   |--- latitude >  -37.78
|   |   |   |   |   |   |   |   |--- value: [36669.00]
|   |   |   |   |   |   |--- balance >  11504.48
|   |   |   |   |   |   |   |--- value: [66128.30]
|   |   |   |   |--- balance >  13276.54
|   |   |   |   |   |--- payment_period_mean_by_bin_age <= 9.88
|   |   |   |   |   |   |--- value: [80069.00]
|   |   |   |   |   |--- payment_period_mean_by_bin_age >  9.88
|   |   |   |   |   |   |--- value: [95863.00]
|   |   |--- balance >  18204.38
|   |   |   |--- payment_period_mean_by_bin_age <= 12.46
|   |   |   |   |--- month <= 9.50
|   |   |   |   |   |--- age <= 35.50
|   |   |   |   |   |   |--- value: [70875.00]
|   |   |   |   |   |--- age >  35.50
|   |   |   |   |   |   |--- latitude <= -37.97
|   |   |   |   |   |   |   |--- value: [34645.00]
|   |   |   |   |   |   |--- latitude >  -37.97
|   |   |   |   |   |   |   |--- payment_period_mean_by_bin_age <= 10.16
|   |   |   |   |   |   |   |   |--- age <= 58.00
|   |   |   |   |   |   |   |   |   |--- value: [40179.00]
|   |   |   |   |   |   |   |   |--- age >  58.00
|   |   |   |   |   |   |   |   |   |--- value: [40798.00]
|   |   |   |   |   |   |   |--- payment_period_mean_by_bin_age >  10.16
|   |   |   |   |   |   |   |   |--- latitude <= -37.87
|   |   |   |   |   |   |   |   |   |--- value: [56835.00]
|   |   |   |   |   |   |   |   |--- latitude >  -37.87
|   |   |   |   |   |   |   |   |   |--- age <= 46.00
|   |   |   |   |   |   |   |   |   |   |--- value: [45829.00]
|   |   |   |   |   |   |   |   |   |--- age >  46.00
|   |   |   |   |   |   |   |   |   |   |--- value: [37464.00]
|   |   |   |   |--- month >  9.50
|   |   |   |   |   |--- longitude <= 145.15
|   |   |   |   |   |   |--- age <= 36.50
|   |   |   |   |   |   |   |--- age <= 34.00
|   |   |   |   |   |   |   |   |--- value: [76641.46]
|   |   |   |   |   |   |   |--- age >  34.00
|   |   |   |   |   |   |   |   |--- value: [127398.00]
|   |   |   |   |   |   |--- age >  36.50
|   |   |   |   |   |   |   |--- longitude <= 144.97
|   |   |   |   |   |   |   |   |--- age <= 44.00
|   |   |   |   |   |   |   |   |   |--- value: [40179.00]
|   |   |   |   |   |   |   |   |--- age >  44.00
|   |   |   |   |   |   |   |   |   |--- value: [37464.00]
|   |   |   |   |   |   |   |--- longitude >  144.97
|   |   |   |   |   |   |   |   |--- age <= 62.00
|   |   |   |   |   |   |   |   |   |--- value: [54771.38]
|   |   |   |   |   |   |   |   |--- age >  62.00
|   |   |   |   |   |   |   |   |   |--- value: [40798.00]
|   |   |   |   |   |--- longitude >  145.15
|   |   |   |   |   |   |--- latitude <= -37.93
|   |   |   |   |   |   |   |--- value: [34645.00]
|   |   |   |   |   |   |--- latitude >  -37.93
|   |   |   |   |   |   |   |--- value: [133116.77]
|   |   |   |--- payment_period_mean_by_bin_age >  12.46
|   |   |   |   |--- month <= 9.50
|   |   |   |   |   |--- value: [81701.00]
|   |   |   |   |--- month >  9.50
|   |   |   |   |   |--- value: [82283.75]
|   |--- latitude >  -37.67
|   |   |--- age <= 27.50

# Deployment

'balance',
	'latitude',	
	'longitude',	
	'age',	
	'payment_period',	
	'month',	
	'payment_period_mean_by_bin_age',
	'day'

In [107]:
data1 = pd.read_excel(r'C:\Users\Hpvictus1\Downloads\income_deploy.xlsx')
data1

,account,age,amount,balance,card_present_flag,customer_id,date,first_name,gender,latitude,longitude,merchant_code,merchant_id,merchant_state,merchant_suburb,movement,status,transaction_id,txn_description,bin_age,year,month,day,hour,minute,dow,payment_period
0,ACC-4258502723,24,116.26,4241.76,1.0,CUS-3378712515,2018-10-08,Kimberly,F,-37.74,145.45,NaN,e7bf57d9-9eeb-41b4-886e-efb676a5bd80,QLD,Port Douglas,debit,authorized,b1e504ecf44840abb3a48b4ab8510f00,SALES-POS,20-30,2018,10,8,13,33,Monday,7
1,ACC-4258502723,24,14.18,5122.49,1.0,CUS-3378712515,2018-10-11,Kimberly,F,-37.74,145.45,NaN,7770e116-8b4a-4d48-b0f5-7a6399958848,VIC,Melton,debit,authorized,dfa272cc57334c7ca87f61a258cb5b90,SALES-POS,20-30,2018,10,11,12,7,Thursday,7
2,ACC-1279356312,44,17.40,5906.28,1.0,CUS-1892177589,2018-08-29,Tyler,M,-37.73,144.79,NaN,8bee9f57-4517-4f80-b7ee-c161f33421e2,VIC,Preston,debit,authorized,d87dc36be2a2414784dd1c84ced28c71,POS,40-50,2018,8,29,9,43,Wednesday,14
3,ACC-1344825761,46,22.00,15729.73,NaN,CUS-1499065773,2018-08-17,Sarah,F,-33.91,151.09,NaN,NaN,NaN,NaN,debit,posted,4d250222351c4fdb90f7a3085f881276,PAYMENT,40-50,2018,8,17,14,0,Friday,14
4,ACC-2171593283,19,33.00,11168.81,NaN,CUS-2317998716,2018-09-06,Fernando,M,-36.04,146.94,NaN,NaN,NaN,NaN,debit,posted,a4154a29a5d642ca9643b402a87e39d3,PAYMENT,<20,2018,9,6,5,0,Thursday,14
5,ACC-240804743,29,56.00,7651.46,NaN,CUS-261674136,2018-08-29,Kenneth,M,-30.75,121.48,NaN,NaN,NaN,NaN,debit,posted,010cfffccf6c4fefb0a7d0b88a6d68da,PAYMENT,20-30,2018,8,29,14,0,Wednesday,14
6,ACC-3954677887,47,24.00,1161.91,NaN,CUS-3716701010,2018-08-11,Ruth,F,-32.28,115.72,NaN,NaN,NaN,NaN,debit,posted,ec40f0d4f9be46f18d93bf86971f38dc,PAYMENT,40-50,2018,8,11,23,0,Saturday,7
7,ACC-2920611728,69,39.12,5215.77,1.0,CUS-1388323263,2018-09-12,Tyler,M,-37.76,144.96,NaN,9cf12ed7-1600-403d-bb24-7f61d51609ef,VIC,Hoppers Crossing,debit,authorized,9c4b758fc15c4aaca329872b206da045,SALES-POS,60-70,2018,9,12,1,12,Wednesday,7
8,ACC-2305712452,18,18.04,2390.88,1.0,CUS-1842679196,2018-08-31,Debra,F,-34.89,138.61,NaN,ae05bf40-b7dc-41a1-8ac1-61c0e8608760,SA,Gilles Plains,debit,authorized,03a5e32154914752a4316fa6663633b6,SALES-POS,<20,2018,8,31,21,19,Friday,7
9,ACC-1710017148,19,16.18,1609.16,1.0,CUS-883482547,2018-08-01,Michelle,F,-34.01,150.82,NaN,499b1c74-d767-43d6-a084-b20d00010c70,NSW,Blacktown,debit,authorized,927d07bdbeb743ebab2865f86132cd99,POS,<20,2018,8,1,14,37,Wednesday,14
10,ACC-574997646,18,1952.29,4135.17,NaN,CUS-586638664,2018-09-21,Mackenzie,F,-33.64,150.79,0.0,NaN,NaN,NaN,credit,posted,81b7a1f6544d42f6b3816f965c807bcf,PAY/SALARY,<20,2018,9,21,14,0,Friday,14
11,ACC-2249586092,19,990.55,6609.23,NaN,CUS-443776336,2018-08-27,Edward,M,-32.07,115.98,0.0,NaN,NaN,NaN,credit,posted,44613cb105574badb087c9c46ade4b6e,PAY/SALARY,<20,2018,8,27,13,0,Monday,7
12,ACC-3881031190,37,86.00,8415.79,NaN,CUS-3201519139,2018-10-24,Richard,M,-21.15,149.19,NaN,NaN,NaN,NaN,debit,posted,c3589ca259eb431c8d1d4daf17b3f417,INTER BANK,30-40,2018,10,24,2,0,Wednesday,7
13,ACC-2901672282,22,106.00,1907.81,NaN,CUS-1617121891,2018-08-08,Daniel,M,-573.00,255.00,NaN,NaN,NaN,NaN,debit,posted,16e03909a85e49e98d5d9c222097c6c4,PAYMENT,20-30,2018,8,8,12,0,Wednesday,14
14,ACC-2901672282,22,74.24,3235.09,1.0,CUS-1617121891,2018-08-23,Daniel,M,-573.00,255.00,NaN,bebf9c8f-f867-42fd-b8f1-35f960d40029,QLD,Molendinar,debit,authorized,718d05436d754a36b6c97f509b5deeeb,SALES-POS,20-30,2018,8,23,14,3,Thursday,14
15,ACC-958000567,34,17.76,8225.28,0.0,CUS-4142663097,2018-09-23,Sandra,F,-12.37,130.90,NaN,c4d6e945-af74-4562-a295-79b8b4a1d2b7,WA,West Perth,debit,authorized,d834e22e4f8a4e07b7b4e18838da41bb,POS,30-40,2018,9,23,10,10,Sunday,14
16,ACC-1598451071,26,33.94,2837.35,1.0,CUS-2487424745,2018-10-08,Diana,F,-27.95,153.41,NaN,1b5cc322-e87a-465f-9bb0-f40b432d5ae9,QLD,Oxenford,debit,authorized,61296ff34cf04c219065d91ca419581a,POS,20-30,2018,10,8,8,49,Monday,7
17,ACC-182446574,27,77.10,9051.67,1.0,CUS-3026014945,2018-10-21,Tonya,F,-32.00,116.06,NaN,fbb901d4-6d0d-4b7a-9b4e-82cd9ec119d5,WA,Mirrabooka,debit,authorized,27a10d70e8f743cab2d1b8c4e35da6b7,POS,20-30,2018,10,21,14,16,Sunday,14
18,ACC-1973887809,26,1098.91,2178.57,NaN,CUS-1646621553,2018-08-15,Antonio,M,-31.90,115.78,0.0,NaN,NaN,NaN,credit,posted,d994adeb38fe444d9cf77d9ea37efff7,PAY/SALARY,20-30,2018,8,15,16,0,Wednesday,7
19,ACC-2828321672,53,49.13,134.78,1.0,CUS-1005756958,2018-08-05,Stephanie,F,-27.51,153.03,NaN,c3a9c01d-1171-4234-9fa8-1b3529504a56,QLD,Red Hill,debit,authorized,2dd568512ff84c55a9b7e834c1128620,SALES-POS,50-60,2018,8,5,3,27,Sunday,7
20,ACC-1598451071,26,3.67,1988.55,1.0,CUS-2487424745,2018-09-16,Diana,F,-27.95,153.41,NaN,eeca8a89-8c38-4312-a6c9-9db0628b3658,QLD,Coolangatta,debit,authorized,dafb9eb0c8214b2b92a89cb6afa0654a,POS,20-30,2018,9,16,23,9,Sunday,7
21,ACC-602667573,40,2280.36,6139.55,NaN,CUS-2031327464,2018-08-20,Michael,M,-33.96,151.23,0.0,NaN,NaN,NaN,credit,posted,ec29a25a35774614a89d87fa42f28f8b,PAY/SALARY,30-40,2018,8,20,14,0,Monday,7
22,ACC-1037050564,40,32.00,4513.77,NaN,CUS-1614226872,2018-10-10,Rhonda,F,-27.66,153.10,NaN,NaN,NaN,NaN,debit,posted,e0cbe4c516a242da972efd5a9e3a19e4,PAYMENT,30-40,2018,10,10,10,0,Wednesday,7
23,ACC-1683215619,38,59.00,8263.89,NaN,CUS-1604596597,2018-09-28,Barry,M,-34.86,138.67,NaN,NaN,NaN,NaN,debit,posted,6a57162929c149099f81c1fce98ede5d,PAYMENT,30-40,2018,9,28,3,0,Friday,0
24,ACC-80388494,28,106.41,5427.32,1.0,CUS-1140341822,2018-09-20,Dustin,M,-37.42,144.97,NaN,142514bf-19ef-4bf7-a00d-aac13c51fbe9,VIC,Ringwood,debit,authorized,214c0efffcda4fa29950400a36123c25,POS,20-30,2018,9,20,13,21,Thursday,14
25,ACC-2776252858,43,28.56,1986.01,1.0,CUS-4123612273,2018-08-03,Kristin,F,-37.76,144.95,NaN,df08814b-3453-493e-8e5f-067ea52e1c22,VIC,Lilydale,debit,authorized,2a248613cafd418ba7184bb2f90f587c,SALES-POS,40-50,2018,8,3,14,0,Friday,7
26,ACC-3541460373,24,39.91,2975.16,1.0,CUS-1433879684,2018-09-22,Jeffrey,M,-37.83,145.00,NaN,98d1a1bd-3c96-42fb-98e8-eeacb5d1ed47,VIC,Melbourne,debit,authorized,4b55dbaa5a714ad0a9df242d39d9f193,POS,20-30,2018,9,22,1,15,Saturday,14
27,ACC-3326339947,22,983.36,7207.55,NaN,CUS-326006476,2018-09-05,Eric,M,-33.80,151.18,0.0,NaN,NaN,NaN,credit,posted,31c01c223a944d488d886c965304ebe2,PAY/SALARY,20-30,2018,9,5,12,0,Wednesday,7
28,ACC-2988263882,44,21.80,2430.08,0.0,CUS-1233833708,2018-08-06,Michael,M,-37.90,145.18,NaN,9af334fc-dbb6-4a51-845e-3f41c7bc8331,VIC,Cheltenham,debit,authorized,56fbca669a5a4d82815ab2b320df36e8,SALES-POS,40-50,2018,8,6,21,9,Monday,7
29,ACC-1608363396,20,24.00,6965.29,NaN,CUS-2688605418,2018-09-27,Robert,M,-33.87,151.22,NaN,NaN,NaN,NaN,debit,posted,e3c09fc7e2a94317bbe074f7b9d79c23,INTER BANK,<20,2018,9,27,11,0,Thursday,14

In [108]:
data1.columns

Index(['account', 'age', 'amount', 'balance', 'card_present_flag',
       'customer_id', 'date', 'first_name', 'gender', 'latitude', 'longitude',
       'merchant_code', 'merchant_id', 'merchant_state', 'merchant_suburb',
       'movement', 'status', 'transaction_id', 'txn_description', 'bin_age',
       'year', 'month', 'day', 'hour', 'minute', 'dow', 'payment_period'],
      dtype='object')

In [109]:
data1["payment_period_mean_by_bin_age"] = data1.groupby("bin_age")["payment_period"].transform("mean")
data1

,account,age,amount,balance,card_present_flag,customer_id,date,first_name,gender,latitude,longitude,merchant_code,merchant_id,merchant_state,merchant_suburb,movement,status,transaction_id,txn_description,bin_age,year,month,day,hour,minute,dow,payment_period,payment_period_mean_by_bin_age
0,ACC-4258502723,24,116.26,4241.76,1.0,CUS-3378712515,2018-10-08,Kimberly,F,-37.74,145.45,NaN,e7bf57d9-9eeb-41b4-886e-efb676a5bd80,QLD,Port Douglas,debit,authorized,b1e504ecf44840abb3a48b4ab8510f00,SALES-POS,20-30,2018,10,8,13,33,Monday,7,10.500000
1,ACC-4258502723,24,14.18,5122.49,1.0,CUS-3378712515,2018-10-11,Kimberly,F,-37.74,145.45,NaN,7770e116-8b4a-4d48-b0f5-7a6399958848,VIC,Melton,debit,authorized,dfa272cc57334c7ca87f61a258cb5b90,SALES-POS,20-30,2018,10,11,12,7,Thursday,7,10.500000
2,ACC-1279356312,44,17.40,5906.28,1.0,CUS-1892177589,2018-08-29,Tyler,M,-37.73,144.79,NaN,8bee9f57-4517-4f80-b7ee-c161f33421e2,VIC,Preston,debit,authorized,d87dc36be2a2414784dd1c84ced28c71,POS,40-50,2018,8,29,9,43,Wednesday,14,9.800000
3,ACC-1344825761,46,22.00,15729.73,NaN,CUS-1499065773,2018-08-17,Sarah,F,-33.91,151.09,NaN,NaN,NaN,NaN,debit,posted,4d250222351c4fdb90f7a3085f881276,PAYMENT,40-50,2018,8,17,14,0,Friday,14,9.800000
4,ACC-2171593283,19,33.00,11168.81,NaN,CUS-2317998716,2018-09-06,Fernando,M,-36.04,146.94,NaN,NaN,NaN,NaN,debit,posted,a4154a29a5d642ca9643b402a87e39d3,PAYMENT,<20,2018,9,6,5,0,Thursday,14,11.666667
5,ACC-240804743,29,56.00,7651.46,NaN,CUS-261674136,2018-08-29,Kenneth,M,-30.75,121.48,NaN,NaN,NaN,NaN,debit,posted,010cfffccf6c4fefb0a7d0b88a6d68da,PAYMENT,20-30,2018,8,29,14,0,Wednesday,14,10.500000
6,ACC-3954677887,47,24.00,1161.91,NaN,CUS-3716701010,2018-08-11,Ruth,F,-32.28,115.72,NaN,NaN,NaN,NaN,debit,posted,ec40f0d4f9be46f18d93bf86971f38dc,PAYMENT,40-50,2018,8,11,23,0,Saturday,7,9.800000
7,ACC-2920611728,69,39.12,5215.77,1.0,CUS-1388323263,2018-09-12,Tyler,M,-37.76,144.96,NaN,9cf12ed7-1600-403d-bb24-7f61d51609ef,VIC,Hoppers Crossing,debit,authorized,9c4b758fc15c4aaca329872b206da045,SALES-POS,60-70,2018,9,12,1,12,Wednesday,7,7.000000
8,ACC-2305712452,18,18.04,2390.88,1.0,CUS-1842679196,2018-08-31,Debra,F,-34.89,138.61,NaN,ae05bf40-b7dc-41a1-8ac1-61c0e8608760,SA,Gilles Plains,debit,authorized,03a5e32154914752a4316fa6663633b6,SALES-POS,<20,2018,8,31,21,19,Friday,7,11.666667
9,ACC-1710017148,19,16.18,1609.16,1.0,CUS-883482547,2018-08-01,Michelle,F,-34.01,150.82,NaN,499b1c74-d767-43d6-a084-b20d00010c70,NSW,Blacktown,debit,authorized,927d07bdbeb743ebab2865f86132cd99,POS,<20,2018,8,1,14,37,Wednesday,14,11.666667
10,ACC-574997646,18,1952.29,4135.17,NaN,CUS-586638664,2018-09-21,Mackenzie,F,-33.64,150.79,0.0,NaN,NaN,NaN,credit,posted,81b7a1f6544d42f6b3816f965c807bcf,PAY/SALARY,<20,2018,9,21,14,0,Friday,14,11.666667
11,ACC-2249586092,19,990.55,6609.23,NaN,CUS-443776336,2018-08-27,Edward,M,-32.07,115.98,0.0,NaN,NaN,NaN,credit,posted,44613cb105574badb087c9c46ade4b6e,PAY/SALARY,<20,2018,8,27,13,0,Monday,7,11.666667
12,ACC-3881031190,37,86.00,8415.79,NaN,CUS-3201519139,2018-10-24,Richard,M,-21.15,149.19,NaN,NaN,NaN,NaN,debit,posted,c3589ca259eb431c8d1d4daf17b3f417,INTER BANK,30-40,2018,10,24,2,0,Wednesday,7,7.000000
13,ACC-2901672282,22,106.00,1907.81,NaN,CUS-1617121891,2018-08-08,Daniel,M,-573.00,255.00,NaN,NaN,NaN,NaN,debit,posted,16e03909a85e49e98d5d9c222097c6c4,PAYMENT,20-30,2018,8,8,12,0,Wednesday,14,10.500000
14,ACC-2901672282,22,74.24,3235.09,1.0,CUS-1617121891,2018-08-23,Daniel,M,-573.00,255.00,NaN,bebf9c8f-f867-42fd-b8f1-35f960d40029,QLD,Molendinar,debit,authorized,718d05436d754a36b6c97f509b5deeeb,SALES-POS,20-30,2018,8,23,14,3,Thursday,14,10.500000
15,ACC-958000567,34,17.76,8225.28,0.0,CUS-4142663097,2018-09-23,Sandra,F,-12.37,130.90,NaN,c4d6e945-af74-4562-a295-79b8b4a1d2b7,WA,West Perth,debit,authorized,d834e22e4f8a4e07b7b4e18838da41bb,POS,30-40,2018,9,23,10,10,Sunday,14,7.000000
16,ACC-1598451071,26,33.94,2837.35,1.0,CUS-2487424745,2018-10-08,Diana,F,-27.95,153.41,NaN,1b5cc322-e87a-465f-9bb0-f40b432d5ae9,QLD,Oxenford,debit,authorized,61296ff34cf04c219065d91ca419581a,POS,20-30,2018,10,8,8,49,Monday,7,10.500000
17,ACC-182446574,27,77.10,9051.67,1.0,CUS-3026014945,2018-10-21,Tonya,F,-32.00,116.06,NaN,fbb901d4-6d0d-4b7a-9b4e-82cd9ec119d5,WA,Mirrabooka,debit,authorized,27a10d70e8f743cab2d1b8c4e35da6b7,POS,20-30,2018,10,21,14,16,Sunday,14,10.500000
18,ACC-1973887809,26,1098.91,2178.57,NaN,CUS-1646621553,2018-08-15,Antonio,M,-31.90,115.78,0.0,NaN,NaN,NaN,credit,posted,d994adeb38fe444d9cf77d9ea37efff7,PAY/SALARY,20-30,2018,8,15,16,0,Wednesday,7,10.500000
19,ACC-2828321672,53,49.13,134.78,1.0,CUS-1005756958,2018-08-05,Stephanie,F,-27.51,153.03,NaN,c3a9c01d-1171-4234-9fa8-1b3529504a56,QLD,Red Hill,debit,authorized,2dd568512ff84c55a9b7e834c1128620,SALES-POS,50-60,2018,8,5,3,27,Sunday,7,7.000000
20,ACC-1598451071,26,3.67,1988.55,1.0,CUS-2487424745,2018-09-16,Diana,F,-27.95,153.41,NaN,eeca8a89-8c38-4312-a6c9-9db0628b3658,QLD,Coolangatta,debit,authorized,dafb9eb0c8214b2b92a89cb6afa0654a,POS,20-30,2018,9,16,23,9,Sunday,7,10.500000
21,ACC-602667573,40,2280.36,6139.55,NaN,CUS-2031327464,2018-08-20,Michael,M,-33.96,151.23,0.0,NaN,NaN,NaN,credit,posted,ec29a25a35774614a89d87fa42f28f8b,PAY/SALARY,30-40,2018,8,20,14,0,Monday,7,7.000000
22,ACC-1037050564,40,32.00,4513.77,NaN,CUS-1614226872,2018-10-10,Rhonda,F,-27.66,153.10,NaN,NaN,NaN,NaN,debit,posted,e0cbe4c516a242da972efd5a9e3a19e4,PAYMENT,30-40,2018,10,10,10,0,Wednesday,7,7.000000
23,ACC-1683215619,38,59.00,8263.89,NaN,CUS-1604596597,2018-09-28,Barry,M,-34.86,138.67,NaN,NaN,NaN,NaN,debit,posted,6a57162929c149099f81c1fce98ede5d,PAYMENT,30-40,2018,9,28,3,0,Friday,0,7.000000
24,ACC-80388494,28,106.41,5427.32,1.0,CUS-1140341822,2018-09-20,Dustin,M,-37.42,144.97,NaN,142514bf-19ef-4bf7-a00d-aac13c51fbe9,VIC,Ringwood,debit,authorized,214c0efffcda4fa29950400a36123c25,POS,20-30,2018,9,20,13,21,Thursday,14,10.500000
25,ACC-2776252858,43,28.56,1986.01,1.0,CUS-4123612273,2018-08-03,Kristin,F,-37.76,144.95,NaN,df08814b-3453-493e-8e5f-067ea52e1c22,VIC,Lilydale,debit,authorized,2a248613cafd418ba7184bb2f90f587c,SALES-POS,40-50,2018,8,3,14,0,Friday,7,9.800000
26,ACC-3541460373,24,39.91,2975.16,1.0,CUS-1433879684,2018-09-22,Jeffrey,M,-37.83,145.00,NaN,98d1a1bd-3c96-42fb-98e8-eeacb5d1ed47,VIC,Melbourne,debit,authorized,4b55dbaa5a714ad0a9df242d39d9f193,POS,20-30,2018,9,22,1,15,Saturday,14,10.500000
27,ACC-3326339947,22,983.36,7207.55,NaN,CUS-326006476,2018-09-05,Eric,M,-33.80,151.18,0.0,NaN,NaN,NaN,credit,posted,31c01c223a944d488d886c965304ebe2,PAY/SALARY,20-30,2018,9,5,12,0,Wednesday,7,10.500000
28,ACC-2988263882,44,21.80,2430.08,0.0,CUS-1233833708,2018-08-06,Michael,M,-37.90,145.18,NaN,9af334fc-dbb6-4a51-845e-3f41c7bc8331,VIC,Cheltenham,debit,authorized,56fbca669a5a4d82815ab2b320df36e8,SALES-POS,40-50,2018,8,6,21,9,Monday,7,9.800000
29,ACC-1608363396,20,24.00,6965.29,NaN,CUS-2688605418,2018-09-27,Robert,M,-33.87,151.22,NaN,NaN,NaN,NaN,debit,posted,e3c09fc7e2a94317bbe074f7b9d79c23,INTER BANK,<20,2018,9,27,11,0,Thursday,14,11.666667

In [110]:
data1 = data1[['customer_id','balance', 'latitude', 'longitude', 'age', 'payment_period', 'month', 'payment_period_mean_by_bin_age', 'day']]

In [111]:
data1

,customer_id,balance,latitude,longitude,age,payment_period,month,payment_period_mean_by_bin_age,day
0,CUS-3378712515,4241.76,-37.74,145.45,24,7,10,10.500000,8
1,CUS-3378712515,5122.49,-37.74,145.45,24,7,10,10.500000,11
2,CUS-1892177589,5906.28,-37.73,144.79,44,14,8,9.800000,29
3,CUS-1499065773,15729.73,-33.91,151.09,46,14,8,9.800000,17
4,CUS-2317998716,11168.81,-36.04,146.94,19,14,9,11.666667,6
5,CUS-261674136,7651.46,-30.75,121.48,29,14,8,10.500000,29
6,CUS-3716701010,1161.91,-32.28,115.72,47,7,8,9.800000,11
7,CUS-1388323263,5215.77,-37.76,144.96,69,7,9,7.000000,12
8,CUS-1842679196,2390.88,-34.89,138.61,18,7,8,11.666667,31
9,CUS-883482547,1609.16,-34.01,150.82,19,14,8,11.666667,1
10,CUS-586638664,4135.17,-33.64,150.79,18,14,9,11.666667,21
11,CUS-443776336,6609.23,-32.07,115.98,19,7,8,11.666667,27
12,CUS-3201519139,8415.79,-21.15,149.19,37,7,10,7.000000,24
13,CUS-1617121891,1907.81,-573.00,255.00,22,14,8,10.500000,8
14,CUS-1617121891,3235.09,-573.00,255.00,22,14,8,10.500000,23
15,CUS-4142663097,8225.28,-12.37,130.90,34,14,9,7.000000,23
16,CUS-2487424745,2837.35,-27.95,153.41,26,7,10,10.500000,8
17,CUS-3026014945,9051.67,-32.00,116.06,27,14,10,10.500000,21
18,CUS-1646621553,2178.57,-31.90,115.78,26,7,8,10.500000,15
19,CUS-1005756958,134.78,-27.51,153.03,53,7,8,7.000000,5
20,CUS-2487424745,1988.55,-27.95,153.41,26,7,9,10.500000,16
21,CUS-2031327464,6139.55,-33.96,151.23,40,7,8,7.000000,20
22,CUS-1614226872,4513.77,-27.66,153.10,40,7,10,7.000000,10
23,CUS-1604596597,8263.89,-34.86,138.67,38,0,9,7.000000,28
24,CUS-1140341822,5427.32,-37.42,144.97,28,14,9,10.500000,20
25,CUS-4123612273,1986.01,-37.76,144.95,43,7,8,9.800000,3
26,CUS-1433879684,2975.16,-37.83,145.00,24,14,9,10.500000,22
27,CUS-326006476,7207.55,-33.80,151.18,22,7,9,10.500000,5
28,CUS-1233833708,2430.08,-37.90,145.18,44,7,8,9.800000,6
29,CUS-2688605418,6965.29,-33.87,151.22,20,14,9,11.666667,27

In [112]:
data1['prediction']=optimized_model.predict(data.iloc[:,1:])
data1

ValueError: The feature names should match those that were passed during fit.
Feature names unseen at fit time:
- amount
- amount_max_by_txn_description
- amount_mean_by_txn_description
- annual_salary
- balance_max_by_merchant_suburb
- ...
Feature names seen at fit time, yet now missing:
- age